// Veritabani genisletme set 41: dunya cografyasi
const NEW_ENTRIES = [
  { k: ['amazon nehri'], a: "Amazon dünyanın en su taşıyan nehridir." },
  { k: ['mississippi nehri'], a: "Mississippi Kuzey Amerika'nın büyük nehridir." },
  { k: ['yangtze | gok nehir'], a: "Yangtze Çin'in en uzun nehridir." },
  { k: ['tuna nehri'], a: "Tuna Avrupa'nın ikinci uzun nehridir." },
  { k: ['ren nehri'], a: "Ren Batı Avrupa'nın işlek nehridir." },
  { k: ['volga nehri'], a: "Volga Avrupa'nın en uzun nehridir." },
  { k: ['ganj nehri'], a: "Ganj Hindistan'ın kutsal nehridir." },
  { k: ['mekong nehri'], a: "Mekong Güneydoğu Asya'nın büyük nehridir." },
  { k: ['alpler | alp daglari'], a: "Alpler Avrupa'nın yüksek sıradağlarıdır." },
  { k: ['and daglari'], a: "Andlar dünyanın en uzun sıradağıdır." },
  { k: ['himalaya | everest dag'], a: "Himalaya Everest'i barındıran sıradağdır." },
  { k: ['kilimanjaro'], a: "Kilimanjaro Afrika'nın en yüksek dağıdır." },
  { k: ['fuji | fujiyama'], a: "Fuji Japonya'nın simge volkanıdır." },
  { k: ['etna | vezuv'], a: "Etna ve Vezüv İtalya'nın ünlü volkanlarıdır." },
  { k: ['aconcagua'], a: "Aconcagua Amerika kıtalarının en yüksek dağıdır." },
  { k: ['hazar denizi | gol mu'], a: "Hazar dünyanın en büyük gölüdür." },
  { k: ['superior golu'], a: "Superior Kuzey Amerika'nın büyük gölüdür." },
  { k: ['victoria golu'], a: "Victoria Afrika'nın büyük gölüdür." },
  { k: ['titicaca'], a: "Titicaca dünyanın en yüksek büyük gölüdür." },
  { k: ['olu deniz'], a: "Ölü Deniz tuzluluğuyla ünlüdür." },
  { k: ['gronland'], a: "Grönland dünyanın en büyük adasıdır." },
  { k: ['borneo | sumatra'], a: "Borneo ve Sumatra Endonezya'nın büyük adalarıdır." },
  { k: ['girit | sicilya'], a: "Girit ve Sicilya Akdeniz'in büyük adalarıdır." },
  { k: ['gobi | kalahari | atacama'], a: "Gobi, Kalahari ve Atacama ünlü çöllerdir." },
  { k: ['panama kanali | suveys kanali'], a: "Panama ve Süveyş kanalları deniz yolunu kısaltır." },
  { k: ['cebelitarik | hurmuz | malakka'], a: "Cebelitarık, Hürmüz ve Malakka ünlü boğazlardır." },
  { k: ['niagara | victoria selale | iguazu'], a: "Niagara, Victoria ve Iguazu ünlü şelalelerdir." },
  { k: ['angel selalesi'], a: "Angel dünyanın en yüksek şelalesidir." },
];
module.exports = NEW_ENTRIES;
