// Veritabani genisletme set 25: deyimler + nezaket sozleri
const NEW_ENTRIES = [
  { k: ['kulak kabartmak'], a: "Kulak kabartmak dikkatle dinlemek demektir." },
  { k: ['goz kulak olmak'], a: "Göz kulak olmak birine ya da şeye dikkat etmek demektir." },
  { k: ['pireyi deve yapmak'], a: "Pireyi deve yapmak küçücük şeyi büyütmek demektir." },
  { k: ['devede kulak'], a: "Devede kulak çok küçük parça demektir." },
  { k: ['tereciye tere satmak'], a: "Tereciye tere satmak bilene iş öğretmeye kalkmak demektir." },
  { k: ['ati alan uskudari gecti'], a: "Atı alan Üsküdar'ı geçti: fırsat kaçtı demektir." },
  { k: ['bal dok yala'], a: "Bal dök yala tertemiz yer demektir." },
  { k: ['parmak isirmak'], a: "Parmak ısırmak şaşkınlıktan ne yapacağını bilememek demektir." },
  { k: ['agzi acik kalmak'], a: "Ağzı açık kalmak çok şaşırmak demektir." },
  { k: ['etekleri zil calmak'], a: "Etekleri zil çalmak sevinçten yerinde duramamak demektir." },
  { k: ['kafasi kazan gibi'], a: "Kafası kazan gibi olmak yorgunluktan düşünememek demektir." },
  { k: ['burnu havada'], a: "Burnu havada olmak kibirli davranmak demektir." },
  { k: ['el ele vermek'], a: "El ele vermek birlikte çalışmak demektir." },
  { k: ['goze girmek'], a: "Göze girmek beğenilmek demektir." },
  { k: ['gozden dusmek'], a: "Gözden düşmek değerini yitirmek demektir." },
  { k: ['kulaktan kulaga'], a: "Kulaktan kulağa fısıltıyla yayılmak demektir." },
  { k: ['gonul almak'], a: "Gönül almak kırılanı hoşnut etmek demektir." },
  { k: ['gecmis olsun ne demek'], a: "Geçmiş olsun hastaya söylenen iyi dilektir." },
  { k: ['basin sag olsun'], a: "Başın sağ olsun vefat edene söylenen taziyedir." },
  { k: ['kolay gelsin'], a: "Kolay gelsin çalışana söylenen iyi dilektir." },
  { k: ['eline saglik'], a: "Eline sağlık emek verene söylenen teşekkürdür." },
  { k: ['afiyet olsun'], a: "Afiyet olsun yemek yiyene söylenir." },
  { k: ['cok yasa | hapşırınca'], a: "Hapşırana çok yaşa denir." },
  { k: ['nazar degmesin | masallah anlami'], a: "Maşallah beğeniyi nazardan korusun diye söylenir." },
  { k: ['hayırlı olsun | hayirli olsun'], a: "Hayırlı olsun yeni şeye söylenen iyi dilektir." },
  { k: ['gule gule kullan'], a: "Güle güle kullan yeni eşyaya söylenir." },
  { k: ['eline diline saglik'], a: "Eline diline sağlık hem işe hem söze teşekkürdür." },
  { k: ['dile dusmek'], a: "Dile düşmek herkesin konuşması olmak demektir." },
  { k: ['gozleri fal tasi'], a: "Gözleri fal taşı gibi açılmak şaşkınlıktan büyümek demektir." },
];
module.exports = NEW_ENTRIES;
