// Veritabani genisletme set 5: teknoloji + spor + doga + saglik + okul
const NEW_ENTRIES = [
  // Teknoloji
  { k: ['internet nedir | wifi nedir'], a: "İnternet bilgisayarları birbirine bağlayan küresel ağdır; wifi kablosuz bağlantı yoludur." },
  { k: ['bluetooth | blutut'], a: "Bluetooth kısa mesafede kablosuz bağlantı teknolojisidir." },
  { k: ['gps | konum servisi'], a: "GPS uydularla konum bulan sistemdir, haritalar onu kullanır." },
  { k: ['qr kod | karekod'], a: "QR kod telefon kamerasıyla okunan iki boyutlu barkoddur." },
  { k: ['5g | 4g fark'], a: "5G, 4G'den çok daha hızlı yeni nesil mobil şebekedir." },
  { k: ['virus bilgisayar | antivirus'], a: "Bilgisayar virüsü zararlı yazılımdır; antivirüs ve güncel sistem korur." },
  { k: ['guclu sifre | sifre guvenligi'], a: "Güçlü şifre uzun olur, her sitede farklı olur, kimseyle paylaşılmaz." },
  { k: ['uydu nedir | haberlesme uydusu'], a: "Haberleşme uyduları TV, internet ve telefon sinyalini uzaya taşır." },
  { k: ['yapay zeka nasil calisir | makine ogrenmesi'], a: "Yapay zeka çok örnekten örüntü öğrenir, ben de küçük bir örneğiyim." },
  { k: ['bilgisayar dondu | telefon kasiyor'], a: "Kasan cihazı yeniden başlat, arka plan uygulamalarını kapat, depolamada yer aç." },
  { k: ['ekran goruntusu | screenshot'], a: "Ekran görüntüsü telefonda genelde güç + ses kısma tuşlarıyla alınır." },
  // Spor
  { k: ['futbol kac kisi | futbol kurallari'], a: "Futbolda her takım 11 kişiyle oynar, maç 90 dakikadır." },
  { k: ['basketbol kac kisi | pota yuksekligi'], a: "Basketbolda her takım 5 kişidir, pota 3,05 metre yüksektedir." },
  { k: ['voleybol kac kisi | file yuksekligi'], a: "Voleybolda her takım 6 kişidir, 3 sette 2 kazanan alır." },
  { k: ['satranc | sah mat'], a: "Satranç 64 karede 16'şar taşla oynanır, amaç şahı mat etmektir." },
  { k: ['yagli gures | kirpinar'], a: "Yağlı güreş Kırkpınar'da yüzyıllardır yapılan ata sporumuzdur." },
  { k: ['okculuk | kemankes'], a: "Okçuluk yayla hedef vurma sporudur, ata sporumuzdandır." },
  { k: ['yuzme stilleri | kulaç'], a: "Yüzmede serbest, kurbağalama, sırtüstü ve kelebek stilleri vardır." },
  { k: ['tenis set | servis'], a: "Teniste maç genelde 2 set alanın olur, servis atışıyla başlar." },
  { k: ['formula 1 | f1'], a: "Formula 1 açık tekerlekli yarışların en üst sınıfıdır." },
  { k: ['maraton kac km'], a: "Maraton 42 kilometre 195 metredir." },
  // Doga
  { k: ['gokkusagi | ebemkusagi'], a: "Gökkuşağı güneş ışığının yağmur damlalarında kırılmasıyla oluşur." },
  { k: ['simsek | yildirim fark'], a: "Şimşek gökyüzündeki elektrik boşalmasıdır, yıldırım yere düşenidir." },
  { k: ['kar nasil olusur | dolu'], a: "Kar bulutlardaki su kristallerinin birleşip düşmesidir." },
  { k: ['hortum | kasirga'], a: "Hortum dönen rüzgar sütunudur, kasırga okyanusta büyüyen fırtınadır." },
  { k: ['gelgit | medcezir'], a: "Gelgit Ay'ın çekimiyle deniz seviyesinin yükselip alçalmasıdır." },
  { k: ['pusula | kuzey nasil bulunur'], a: "Pusulanın renkli ucu kuzeyi gösterir; yosunlar ağacın kuzeyinde olur." },
  { k: ['cig | cig dusmesi'], a: "Çiy gece soğuyan yüzeyde havadaki nemin yoğunlaşmasıdır." },
  { k: ['sis | pus'], a: "Sis yere yakın bulut demektir, görüşü azaltır." },
  { k: ['volkan | yanardag patlamasi'], a: "Yanardağ yeraltındaki magmanın yüzeye çıkmasıdır." },
  { k: ['magara | damlataş'], a: "Mağaralar suda eriyen kayaların oyulmasıyla oluşur, sarkıtlar tavandandır." },
  // Saglik
  { k: ['ates kac normal | vucut isisi'], a: "Normal vücut ısısı 36-37 derecedir, 38 üstü ateştir." },
  { k: ['grip | soguk alginligi fark'], a: "Grip ani başlar, soğuk algınlığı hafiftir; ikisinde de dinlenme ve sıvı gerekir." },
  { k: ['bas agrisi | basim agriyor'], a: "Baş ağrısında su iç, dinlen, ekran molası ver. Sık oluyorsa doktora git." },
  { k: ['dis agrisi | disim agriyor'], a: "Diş ağrısında ılık tuzlu suyla gargara yap, en kısa sürede dişçiye git." },
  { k: ['gunes carpmasi | sicak carpmasi'], a: "Güneş çarpmasında serine geç, su iç, ıslak bez koy. Bilinç bulanırsa 112." },
  { k: ['gunde kac litre su | su icmek'], a: "Günde yaklaşık 2 litre su içmek önerilir." },
  { k: ['kac saat uyku | uyku suresi'], a: "Yetişkin için 7-8 saat uyku önerilir." },
  { k: ['oksuruk | bogaz agrisi'], a: "Boğaz ağrısında ılık içecekler ve dinlenme iyi gelir, geçmezse doktora git." },
  { k: ['alerji | hapşirik | hapsirik'], a: "Alerji hapşırık ve kaşıntı yapar, toz ve polen tetikler. Şiddetliyse doktora danış." },
  // Okul
  { k: ['pi sayisi | 3.14'], a: "Pi sayısı yaklaşık 3,14'tür, dairenin çevresinin çapına oranıdır." },
  { k: ['asal sayi | asal sayilar'], a: "Asal sayı 1 ve kendisinden başkasına bölünmeyendir: 2, 3, 5, 7, 11..." },
  { k: ['ucgen cesitleri | dik ucgen'], a: "Üçgenler kenarına göre eşkenar, ikizkenar ve çeşitkenardır." },
  { k: ['kesir | pay payda'], a: "Kesirde üstteki pay, alttaki paydadır; payda kaç parçaya bölündüğünü gösterir." },
  { k: ['yuzde hesaplama | yuzde nedir'], a: "Yüzde bir sayının yüze bölümüdür; %20 demek beşte bir demektir." },
  { k: ['uslu sayi | kare karekok'], a: "Üslü sayıda taban kendisiyle üs kadar çarpılır; 3² = 9'dur." },
  { k: ['metre kac cm | 1 km kac m'], a: "1 metre 100 santim, 1 kilometre 1000 metredir." },
  { k: ['hafta kac gun | yil kac gun'], a: "Hafta 7 gün, yıl 365 gündür (artık yılda 366)." },
  { k: ['alfabe kac harf | turk alfabesi'], a: "Türk alfabesinde 29 harf vardır." },
  { k: ['noktalama | virgul nokta'], a: "Cümle büyük harfle başlar, sonuna nokta konur; sıralamada virgül kullanılır." },
];
module.exports = NEW_ENTRIES;
