// Veritabani genisletme set 40: kalan baskentler
const NEW_ENTRIES = [
  { k: ['vatikan baskenti'], a: "Vatikan'ın başkenti Vatikan'dır." },
  { k: ['monako baskenti'], a: "Monako'nun başkenti Monako'dur." },
  { k: ['lihtenstayn baskenti | vaduz'], a: "Lihtenştayn'ın başkenti Vaduz'dur." },
  { k: ['san marino baskenti'], a: "San Marino'nun başkenti San Marino'dur." },
  { k: ['luksemburg baskenti'], a: "Lüksemburg'un başkenti Lüksemburg'dur." },
  { k: ['malta baskenti | valletta'], a: "Malta'nın başkenti Valletta'dır." },
  { k: ['kibris baskenti | lefkosa'], a: "Kıbrıs'ın başkenti Lefkoşa'dır." },
  { k: ['estonya baskenti | tallin'], a: "Estonya'nın başkenti Tallin'dir." },
  { k: ['letonya baskenti | riga'], a: "Letonya'nın başkenti Riga'dır." },
  { k: ['litvanya baskenti | vilnius'], a: "Litvanya'nın başkenti Vilnius'tur." },
  { k: ['slovakya baskenti | bratislava'], a: "Slovakya'nın başkenti Bratislava'dır." },
  { k: ['slovenya baskenti | lubliyana'], a: "Slovenya'nın başkenti Lübliyana'dır." },
  { k: ['hirvatistan baskenti | zagrep'], a: "Hırvatistan'ın başkenti Zagrep'tir." },
  { k: ['sirbistan baskenti | belgrad'], a: "Sırbistan'ın başkenti Belgrad'dır." },
  { k: ['bosna baskenti | saraybosna'], a: "Bosna-Hersek'in başkenti Saraybosna'dır." },
  { k: ['karadag baskenti | podgoritsa'], a: "Karadağ'ın başkenti Podgoritsa'dır." },
  { k: ['kosova baskenti | pristina'], a: "Kosova'nın başkenti Priştine'dir." },
  { k: ['makedonya baskenti | uskup'], a: "Kuzey Makedonya'nın başkenti Üsküp'tür." },
  { k: ['moldova baskenti | kisinev'], a: "Moldova'nın başkenti Kişinev'dir." },
  { k: ['belarus baskenti | minsk'], a: "Belarus'un başkenti Minsk'tir." },
  { k: ['turkmenistan baskenti | askabat'], a: "Türkmenistan'ın başkenti Aşkabat'tır." },
  { k: ['kirgizistan baskenti | biskek'], a: "Kırgızistan'ın başkenti Bişkek'tir." },
  { k: ['tacikistan baskenti | dusanbe'], a: "Tacikistan'ın başkenti Duşanbe'dir." },
  { k: ['afganistan baskenti | kabil'], a: "Afganistan'ın başkenti Kabil'dir." },
  { k: ['laos baskenti | vientiane'], a: "Laos'un başkenti Vientiane'dir." },
  { k: ['kambocya baskenti | phnom penh'], a: "Kamboçya'nın başkenti Phnom Penh'dir." },
  { k: ['mogolistan baskenti | ulan batur'], a: "Moğolistan'ın başkenti Ulan Batur'dur." },
  { k: ['kuzey kore baskenti | pyongyang'], a: "Kuzey Kore'nin başkenti Pyongyang'dır." },
  { k: ['sri lanka baskenti | kolombo'], a: "Sri Lanka'nın başkenti Kolombo'dur." },
  { k: ['nepal baskenti | katmandu'], a: "Nepal'in başkenti Katmandu'dur." },
  { k: ['butan baskenti | timpu'], a: "Butan'ın başkenti Timpu'dur." },
  { k: ['banglades baskenti | dakka'], a: "Bangladeş'in başkenti Dakka'dır." },
  { k: ['maldivler baskenti | male'], a: "Maldivler'in başkenti Male'dir." },
  { k: ['umman baskenti | maskat'], a: "Umman'ın başkenti Maskat'tır." },
  { k: ['yemen baskenti | sana'], a: "Yemen'in başkenti Sana'dır." },
  { k: ['urdun baskenti | amman'], a: "Ürdün'ün başkenti Amman'dır." },
  { k: ['lubnan baskenti | beyirut'], a: "Lübnan'ın başkenti Beyrut'tur." },
  { k: ['suriye baskenti | sam'], a: "Suriye'nin başkenti Şam'dır." },
  { k: ['katar baskenti | doha'], a: "Katar'ın başkenti Doha'dır." },
  { k: ['kuveyt baskenti'], a: "Kuveyt'in başkenti Kuveyt'tir." },
  { k: ['bahreyn baskenti | manama'], a: "Bahreyn'in başkenti Manama'dır." },
  { k: ['kosta rika baskenti | san jose'], a: "Kosta Rika'nın başkenti San Jose'dir." },
  { k: ['panama baskenti'], a: "Panama'nın başkenti Panama'dır." },
  { k: ['jamaika baskenti | kingston'], a: "Jamaika'nın başkenti Kingston'dır." },
  { k: ['haiti baskenti | port au prince'], a: "Haiti'nin başkenti Port-au-Prince'dir." },
  { k: ['bolivya baskenti | sucre | la paz'], a: "Bolivya'nın başkentleri Sucre ve La Paz'dır." },
  { k: ['paraguay baskenti | asuncion'], a: "Paraguay'ın başkenti Asunción'dur." },
  { k: ['uruguay baskenti | montevideo'], a: "Uruguay'ın başkenti Montevideo'dur." },
  { k: ['senegal baskenti | dakar'], a: "Senegal'in başkenti Dakar'dır." },
  { k: ['mali baskenti | bamako'], a: "Mali'nin başkenti Bamako'dur." },
  { k: ['nijer baskenti | niamey'], a: "Nijer'in başkenti Niamey'dir." },
  { k: ['cad baskenti'], a: "Çad'ın başkenti N'Djamena'dır." },
  { k: ['sudan baskenti | hartum'], a: "Sudan'ın başkenti Hartum'dur." },
  { k: ['somali baskenti | mogadisu'], a: "Somali'nin başkenti Mogadişu'dur." },
  { k: ['tanzanya baskenti | dodoma'], a: "Tanzanya'nın başkenti Dodoma'dır." },
  { k: ['uganda baskenti | kampala'], a: "Uganda'nın başkenti Kampala'dır." },
  { k: ['ruanda baskenti | kigali'], a: "Ruanda'nın başkenti Kigali'dir." },
  { k: ['kongo baskenti | kinsasa'], a: "Kongo'nun başkenti Kinşasa'dır." },
  { k: ['angola baskenti | luanda'], a: "Angola'nın başkenti Luanda'dır." },
  { k: ['zambiya baskenti | lusaka'], a: "Zambiya'nın başkenti Lusaka'dır." },
  { k: ['zimbabve baskenti | harare'], a: "Zimbabve'nin başkenti Harare'dir." },
  { k: ['botsvana baskenti | gaborone'], a: "Botsvana'nın başkenti Gaborone'dir." },
  { k: ['namibya baskenti | windhoek'], a: "Namibya'nın başkenti Windhoek'tur." },
  { k: ['mozambik baskenti | maputo'], a: "Mozambik'in başkenti Maputo'dur." },
  { k: ['madagaskar baskenti | antananarivo'], a: "Madagaskar'ın başkenti Antananarivo'dur." },
  { k: ['kamerun baskenti | yaounde'], a: "Kamerun'un başkenti Yaoundé'dir." },
  { k: ['gabon baskenti | librevil'], a: "Gabon'un başkenti Librevil'dir." },
  { k: ['gana baskenti | akra'], a: "Gana'nın başkenti Akra'dır." },
  { k: ['liberya baskenti | monrovia'], a: "Liberya'nın başkenti Monrovia'dır." },
  { k: ['moritanya baskenti | nuaksot'], a: "Moritanya'nın başkenti Nuakşot'tur." },
  { k: ['cibuti baskenti'], a: "Cibuti'nin başkenti Cibuti'dir." },
  { k: ['eritre baskenti | asmara'], a: "Eritre'nin başkenti Asmara'dır." },
];
module.exports = NEW_ENTRIES;
