// Veritabani genisletme set 9: meslekler + tasitlar + gunluk hayat
const NEW_ENTRIES = [
  // Meslekler
  { k: ['doktor ne is yapar | hekimlik'], a: "Doktor hasta muayene eder, teşhis koyar, tedavi planlar." },
  { k: ['ogretmen ne is yapar | ogretmenlik'], a: "Öğretmen öğrencilere ders anlatır, okulda eğitim verir." },
  { k: ['muhendis | muhendislik dallari'], a: "Mühendis tasarlar ve üretir; inşaat, makine, elektrik gibi dalları vardır." },
  { k: ['avukat | hukukcu'], a: "Avukat mahkemede müvekkilini savunur." },
  { k: ['hakim | savci fark'], a: "Hakim karar verir, savcı suçlamayı hazırlar." },
  { k: ['polis ne is yapar | emniyet'], a: "Polis güvenliği sağlar, suçla mücadele eder." },
  { k: ['itfaiyeci | yangin sondurme'], a: "İtfaiyeci yangın söndürür, kazada kurtarma yapar." },
  { k: ['hemsire | ebe fark'], a: "Hemşire hastaya bakar, doktorun tedavisini uygular." },
  { k: ['eczaci'], a: "Eczacı ilaç hazırlar ve ilaç kullanımı anlatır." },
  { k: ['disci | dis hekimi'], a: "Dişçi diş çeker, dolgu yapar, diş sağlığına bakar." },
  { k: ['veteriner'], a: "Veteriner hayvanları tedavi eder." },
  { k: ['mimar | ics mimar fark'], a: "Mimar bina tasarlar, iç mimar iç mekan düzenler." },
  { k: ['muhasebeci | mali musavir'], a: "Muhasebeci hesap ve vergi işlerini tutar." },
  { k: ['gazeteci | muhabir'], a: "Gazeteci haber toplar ve yazar." },
  { k: ['asçi | sef fark'], a: "Aşçı yemek pişirir, şef mutfağı yönetir." },
  { k: ['berber | kuafor fark'], a: "Berber erkek, kuaför genelde kadın saçı keser." },
  { k: ['terzi'], a: "Terzi kıyafet diker ve tamir eder." },
  { k: ['tesisatci | elektrikci'], a: "Tesisatçı su, elektrikçi elektrik işleri yapar." },
  { k: ['marangoz'], a: "Marangoz ahşap mobilya yapar." },
  { k: ['ciftci | rençber'], a: "Çiftçi tarla eker, ürün yetiştirir." },
  { k: ['balikci'], a: "Balıkçı ağla veya oltayla balık tutar." },
  { k: ['pilot | kaptan pilot'], a: "Pilot uçağı uçurur, kaptan pilot sorumludur." },
  { k: ['hostes | kabin memuru'], a: "Kabin memuru uçakta yolcuya hizmet eder." },
  { k: ['sofor | kaptan sofor'], a: "Şoför araba, otobüs gibi taşıtları sürer." },
  { k: ['kargo | kurye'], a: "Kurye paket taşır, kargo şirketi gönderiyi ulaştırır." },
  // Tasitlar
  { k: ['ucak nasil ucar | kaldirma kuvveti'], a: "Uçak kanatlarının kaldırma kuvvetiyle uçar." },
  { k: ['helikopter | pervane'], a: "Helikopter üst pervanesiyle dikey inip kalkar." },
  { k: ['gemi | vapur fark'], a: "Vapur kısa mesafe yolcu taşır, gemi genel addır." },
  { k: ['denizalti'], a: "Denizaltı suyun altında ilerleyen askeri araçtır." },
  { k: ['tren cesitleri | hizli tren kac km'], a: "Hızlı tren saatte 250 km üstü hız yapar." },
  { k: ['metro | tramvay fark'], a: "Metro yeraltından, tramvay sokaktan rayla gider." },
  { k: ['traktor'], a: "Traktör tarlada kullanılan güçlü iş aracıdır." },
  { k: ['kamyon | tir fark'], a: "Tır çekici ve dorseden oluşur, kamyondan büyüktür." },
  { k: ['motosiklet | kask'], a: "Motosiklette kask takmak zorunludur." },
  { k: ['bisiklet vites | fren'], a: "Bisiklette vites hızı, fren durmayı sağlar." },
  { k: ['balon | zeplin fark'], a: "Sıcak hava balonu ısınan havayla yükselir." },
  // Gunluk hayat
  { k: ['camasir kac derece | leke cikarma'], a: "Beyazlar 60, renkliler 30-40 derecede yıkanır; lekeye önce soğuk su tutulur." },
  { k: ['yemek tuzu | kaya tuzu fark'], a: "Sofra tuzu incedir, kaya tuzu doğaldır; aşırısı tansiyonu yükseltir." },
  { k: ['sut nasil saklanir | son kullanma'], a: "Açılan süt buzdolabında 2-3 günde tüketilir." },
  { k: ['yumurta taze mi | su testi'], a: "Yumurta suda yatay durursa taze, dik durursa bayattır." },
  { k: ['ekmek nasil saklanir | bayat ekmek'], a: "Ekmek bez torbada saklanır, bayadı küflenmeden kurutulup değerlendirilir." },
  { k: ['elektrik tasarrufu | fatura dusurme'], a: "Tasarruf için LED ampul, A++ cihaz ve gereksiz ışığı kapatmak gerekir." },
  { k: ['su tasarrufu'], a: "Diş fırçalarken musluğu kapatmak ve kısa duş su tasarrufu sağlar." },
  { k: ['camasir suyu | deterjan fark'], a: "Çamaşır suyu ağartır ve dezenfekte eder, deterjan kir çözer." },
  { k: ['utu sicakligi | kumas'], a: "Pamuk yüksek, sentetik düşük ısıda ütülenir." },
  { k: ['kapi zili | diafon'], a: "Diafon kapıdakiyle konuşup kapıyı açmayı sağlar." },
];
module.exports = NEW_ENTRIES;
