// Veritabani genisletme set 3: turk yemekleri
const NEW_ENTRIES = [
  { k: ['baklava | antep baklavasi'], a: "Baklava ince yufka, fıstık ve şerbetle yapılan ünlü Türk tatlısıdır." },
  { k: ['adana kebap | adana kebabi'], a: "Adana kebap acılı kıymanın şişte pişirilmesiyle yapılır." },
  { k: ['urfa kebap | urfa kebabi'], a: "Urfa kebap Adana'nın acısız halidir, bulgur pilavıyla yenir." },
  { k: ['doner | doner kebap'], a: "Döner dikey şişte pişen etin ince kesilmesiyle yapılır." },
  { k: ['lahmacun'], a: "Lahmacun kıymalı harcın ince hamur üstünde fırınlanmasıdır." },
  { k: ['pide | kir pidesi | kiymali pide'], a: "Pide hamur üstüne kıyma, kaşar veya yumurta konup fırınlanır." },
  { k: ['manti | kayseri mantisi'], a: "Mantı küçük hamurların kıymayla doldurulup yoğurtla yenmesidir, Kayseri meşhurdur." },
  { k: ['simit | gevrek'], a: "Simit susamlı halka ekmektir; İzmir'de gevrek denir." },
  { k: ['turk kahvesi | kahve falı | kahve fali'], a: "Türk kahvesi cezvede pişirilir, telvesiyle ünlüdür." },
  { k: ['lokum | turk lokumu'], a: "Lokum nişasta ve şekerle yapılan yumuşak şekerlemedir." },
  { k: ['asure | asure gunu'], a: "Aşure buğday, nohut ve kuru meyvelerle yapılan paylaşımlık tatlıdır." },
  { k: ['kunefe | hatay kunefesi'], a: "Künefe peynirli kadayıfın şerbetle buluşmasıdır, Hatay meşhurdur." },
  { k: ['menemen'], a: "Menemen yumurta, domates ve biberle yapılan tavalık yemektir." },
  { k: ['mercimek corbasi | kirmizi mercimek'], a: "Mercimek çorbası kırmızı mercimekle yapılan besleyici başlangıçtır." },
  { k: ['dolma | biber dolmasi'], a: "Dolma biber, yaprak gibi sebzelerin pirinçli harçla doldurulmasıdır." },
  { k: ['sarma | yaprak sarmasi'], a: "Sarma asma yaprağına pirinçli harç sarılmasıyla yapılır." },
  { k: ['pilav | bulgur pilavi | pirinc pilavi'], a: "Pilav pirinç veya bulgurdan yapılır, ana yemeğin yanına konur." },
  { k: ['ayran'], a: "Ayran yoğurt, su ve tuzla yapılan serinletici içecektir." },
  { k: ['boza | vefa bozasi'], a: "Boza darıdan yapılan koyu, mayhoş kış içeceğidir." },
  { k: ['salep | sahlep'], a: "Salep orkide kökünden yapılan sıcak sütlü kış içeceğidir." },
  { k: ['tursu | tursu suyu'], a: "Turşu sebzelerin sirke-tuzlu suda bekletilmesiyle yapılır." },
  { k: ['midye dolma'], a: "Midye dolma midye içine baharatlı pirinç doldurulmasıyla yapılır." },
  { k: ['kokorec'], a: "Kokoreç kuzu bağırsağının şişte pişirilip doğranmasıdır." },
  { k: ['tantuni | mersin tantunisi'], a: "Tantuni ince doğranmış etin lavaşta dürüm yapılmasıdır, Mersin meşhurdur." },
  { k: ['cig kofte | etsiz cig kofte'], a: "Çiğ köfte bulgur ve baharatla yoğrulan etsiz atıştırmalıktır." },
  { k: ['hamsi | hamsi tava'], a: "Hamsi Karadeniz'in küçük balığıdır, tava ve buğulaması yapılır." },
  { k: ['mihlama | muhlama | kuymak'], a: "Mıhlama peynir, tereyağı ve mısır unuyla yapılan Karadeniz yemeğidir." },
  { k: ['testi kebabi | avanos testi'], a: "Testi kebabı etin testi içinde fırınlanıp kırılarak açılmasıdır." },
  { k: ['iskender | bursa iskenderi'], a: "İskender dönerin yoğurt, tereyağı ve domates sosla servisidir, Bursa meşhurdur." },
  { k: ['cay nasil demlenir | iyi cay'], a: "İyi çay alt demliğe çay, üste su konup kısık ateşte 15 dakika demlenir." },
  { k: ['sutlac | firin sutlac'], a: "Sütlaç pirinç ve sütle yapılan tatlıdır, fırınlanmışı meşhurdur." },
  { k: ['kazandibi'], a: "Kazandibi dibi karamelize süt tatlısıdır." },
  { k: ['tulumba | halka tatli'], a: "Tulumba şerbetli hamur tatlısıdır." },
  { k: ['revani | irmik tatlisi'], a: "Revani irmikli şerbetli kek tatlısıdır." },
  { k: ['kadayif | tel kadayif'], a: "Kadayıf tel hamurla yapılan şerbetli tatlıdır." },
];
module.exports = NEW_ENTRIES;
