// Veritabani genisletme set 13: mutfak derinlestirme
const NEW_ENTRIES = [
  { k: ['beyti | alinazik'], a: "Beyti lavaşa sarılı kebaptır, alinazik patlıcan beğendili kebaptır." },
  { k: ['hunkar begendi'], a: "Hünkâr beğendi patlıcan beğendili et yemeğidir." },
  { k: ['karniyarik | imam bayildi'], a: "Karnıyarık kıymalı, imam bayıldı zeytinyağlı patlıcan yemeğidir." },
  { k: ['kuru fasulye | pilav ustu'], a: "Kuru fasulye pilavın efsane eşlikçisidir." },
  { k: ['mercimek koftesi | kisir fark'], a: "Mercimek köftesi ve kısır bulgurlu soğuk atıştırmalıklardır." },
  { k: ['pogaca | acma fark'], a: "Poğaça ve açma mayalı hamur işleridir." },
  { k: ['katmer | bazlama | lavas'], a: "Katmer çıtır, bazlama yumuşak, lavaş ince ekmektir." },
  { k: ['tarhana | ezogelin | yayla corbasi'], a: "Tarhana, ezogelin ve yayla Türk mutfağının ünlü çorbalarıdır." },
  { k: ['kelle paca | iskembe'], a: "Kelle paça ve işkembe şifalı sayılan çorbalardır." },
  { k: ['beyran'], a: "Beyran Gaziantep'in acılı etli çorbasıdır." },
  { k: ['sis kebap | tavuk sis | cop sis'], a: "Şiş kebap etin şişte pişmesidir, tavuk ve çöp şiş çeşitleridir." },
  { k: ['tandir | kuyu kebabi | guvec'], a: "Tandır, kuyu kebabı ve güveç yavaş pişen et yemekleridir." },
  { k: ['yaglama | kayseri yaglamasi'], a: "Yağlama Kayseri'nin kat kat etli yemeğidir." },
  { k: ['arabasi | keskek'], a: "Keşkek buğday ve etin dövülmesiyle yapılır, düğün yemeğidir." },
  { k: ['hosmerim'], a: "Höşmerim peynirli tatlıdır." },
  { k: ['kabak tatlisi | ayva tatlisi'], a: "Kabak ve ayva tatlısı şerbetli meyve tatlılarıdır." },
  { k: ['gullac | ramazan tatlisi | gullac ne zaman'], a: "Güllaç ramazanın sütlü gül sulu tatlısıdır." },
  { k: ['keskul | tavuk gogsu'], a: "Keşkül bademli, tavuk göğsü tavuk etli süt tatlısıdır." },
  { k: ['maras dondurmasi | kesme dondurma'], a: "Maraş dondurması salepli, uzayan kıvamlıdır." },
  { k: ['sekerpare | kalbura basti | vezir parmagi'], a: "Şekerpare, kalburabastı ve vezir parmağı şerbetli hamur tatlılarıdır." },
  { k: ['lokma | izmir lokmasi'], a: "Lokma kızarmış hamurun şerbete atılmasıdır." },
  { k: ['pismaniye | cekme helva'], a: "Pişmaniye tel tel çekilen helvadır." },
  { k: ['cezerye | mesir macunu'], a: "Cezerye havuçlu, mesir macunu baharatlı tatlılardır." },
  { k: ['osmanli serbeti | sira | hardaliye'], a: "Osmanlı şerbeti meyveli, hardaliye üzümlü geleneksel içeceklerdir." },
  { k: ['pizza | margarita'], a: "Pizza İtalyan hamur işidir, margarita klasik çeşididir." },
  { k: ['makarna | spagetti'], a: "Makarna İtalyan hamur işidir, spagetti uzun çeşididir." },
  { k: ['hamburger | cheeseburger'], a: "Hamburger köfteli sandviçtir." },
  { k: ['susi | sashimi'], a: "Suşi çiğ balıklı Japon yemeğidir." },
  { k: ['tacos | meksika yemegi'], a: "Tacos mısır tortillalı Meksika yemeğidir." },
  { k: ['noodle | ramen'], a: "Noodle Uzakdoğu eriştesidir, ramen çorbalı çeşididir." },
  { k: ['kruvasan | pankek | waffle'], a: "Kruvasan katmanlı, pankek tavalık, waffle ızgaralık hamur işleridir." },
];
module.exports = NEW_ENTRIES;
