// Veritabani genisletme set 42: kalan para birimleri
const NEW_ENTRIES = [
  { k: ['tayland para birimi | baht'], a: "Tayland'ın para birimi bahttır." },
  { k: ['romanya para birimi | ley'], a: "Romanya'nın para birimi leydir." },
  { k: ['bulgaristan para birimi | lev'], a: "Bulgaristan'ın para birimi levdir." },
  { k: ['sirbistan para birimi | dinar sirp'], a: "Sırbistan'ın para birimi dinardır." },
  { k: ['hirvatistan para birimi | euro mu'], a: "Hırvatistan euro kullanır." },
  { k: ['arjantin para birimi | pezo arjantin'], a: "Arjantin'in para birimi pezodur." },
  { k: ['sili para birimi | pezo sili'], a: "Şili'nin para birimi pezodur." },
  { k: ['pakistan para birimi | rupi pakistan'], a: "Pakistan'ın para birimi rupidir." },
  { k: ['banglades para birimi | taka'], a: "Bangladeş'in para birimi takadır." },
  { k: ['mogolistan para birimi | tugrik'], a: "Moğolistan'ın para birimi tugriktir." },
  { k: ['azerbaycan para birimi | manat'], a: "Azerbaycan'ın para birimi manattır." },
  { k: ['gurcistan para birimi | lari'], a: "Gürcistan'ın para birimi laridir." },
  { k: ['ermenistan para birimi | dram'], a: "Ermenistan'ın para birimi dramdır." },
  { k: ['kazakistan para birimi | tenge'], a: "Kazakistan'ın para birimi tengedir." },
  { k: ['kenya para birimi | silin'], a: "Kenya'nın para birimi şilindir." },
  { k: ['nijerya para birimi | naira'], a: "Nijerya'nın para birimi nairadır." },
  { k: ['gana para birimi | sedi'], a: "Gana'nın para birimi sedidir." },
  { k: ['guney afrika para birimi | rand'], a: "Güney Afrika'nın para birimi randdır." },
  { k: ['etiyopya para birimi | birr'], a: "Etiyopya'nın para birimi birrdir." },
  { k: ['misir para birimi | misir lirasi'], a: "Mısır'ın para birimi liradır." },
  { k: ['yeni zelanda para birimi | dolar nz'], a: "Yeni Zelanda'nın para birimi dolardır." },
  { k: ['singapur para birimi | dolar sg'], a: "Singapur'un para birimi dolardır." },
  { k: ['hong kong para birimi | dolar hk'], a: "Hong Kong'un para birimi dolardır." },
  { k: ['israil para birimi | sekel'], a: "İsrail'in para birimi şekeldir." },
  { k: ['endonezya para birimi | rupih'], a: "Endonezya'nın para birimi rupiahtır." },
  { k: ['malezya para birimi | ringgit'], a: "Malezya'nın para birimi ringgittir." },
  { k: ['filipinler para birimi | pezo filipin'], a: "Filipinler'in para birimi pezodur." },
];
module.exports = NEW_ENTRIES;
