// Veritabani genisletme set 26: ruya tabirleri (geleneksel yorum "derler" cercevesinde)
const RAW = [
  ['ruyada su gormek', 'Rüyada su görmek hayra yorulur derler.'],
  ['ruyada deniz gormek', 'Rüyada deniz görmek gönül ferahlığı derler.'],
  ['ruyada ucmak', 'Rüyada uçmak özgürlük ve yükseliş derler.'],
  ['ruyada yilan gormek', 'Rüyada yılan görmek dikkatli ol derler.'],
  ['ruyada dis dusmesi', 'Rüyada diş düşmesi değişim derler.'],
  ['ruyada bebek gormek', 'Rüyada bebek görmek yenilik derler.'],
  ['ruyada para gormek', 'Rüyada para görmek kazanç derler.'],
  ['ruyada altin gormek', 'Rüyada altın görmek kısmet derler.'],
  ['ruyada ev gormek', 'Rüyada ev görmek huzur derler.'],
  ['ruyada araba surmek', 'Rüyada araba sürmek hayatın yönü derler.'],
  ['ruyada okul gormek', 'Rüyada okul görmek öğrenme dönemi derler.'],
  ['ruyada sinav gormek', 'Rüyada sınav görmek sorumluluk kaygısı derler.'],
  ['ruyada dugun gormek', 'Rüyada düğün görmek sevinç derler.'],
  ['ruyada aglamak', 'Rüyada ağlamak ferahlama derler.'],
  ['ruyada gulmek', 'Rüyada gülmek sevinç derler.'],
  ['ruyada kosmak', 'Rüyada koşmak hedefe ilerleme derler.'],
  ['ruyada dusmek', 'Rüyada düşmek tedirginlik derler.'],
  ['ruyada kovalanmak', 'Rüyada kovalanmak kaçılan sorun derler.'],
  ['ruyada yagmur gormek', 'Rüyada yağmur görmek bereket derler.'],
  ['ruyada kar gormek', 'Rüyada kar görmek temiz sayfa derler.'],
  ['ruyada gunes gormek', 'Rüyada güneş görmek umut derler.'],
  ['ruyada ay gormek', 'Rüyada ay görmek sezgiler derler.'],
  ['ruyada yildiz gormek', 'Rüyada yıldız görmek dilek derler.'],
  ['ruyada cicek gormek', 'Rüyada çiçek görmek mutluluk derler.'],
  ['ruyada kedi gormek', 'Rüyada kedi görmek bağımsızlık derler.'],
  ['ruyada kopek gormek', 'Rüyada köpek görmek sadakat derler.'],
  ['ruyada kus gormek', 'Rüyada kuş görmek haber derler.'],
  ['ruyada balik gormek', 'Rüyada balık görmek kısmet derler.'],
  ['ruyada ekmek gormek', 'Rüyada ekmek görmek rızık derler.'],
  ['ruyada olum gormek', 'Rüyada ölüm görmek uzun ömür derler.'],
];
const NEW_ENTRIES = RAW.map(([k, a]) => ({ k: [k], a: a + ' (Eğlencesine bakıldı.)' }));
module.exports = NEW_ENTRIES;
