// Veritabani genisletme set 18: edebiyat klasikleri
const NEW_ENTRIES = [
  // Turk
  { k: ['omer seyfettin | kasagi | falaka'], a: "Ömer Seyfettin Kaşağı ve Falaka'nın yazarıdır." },
  { k: ['resat nuri | calikusu'], a: "Reşat Nuri Çalıkuşu'nun yazarıdır." },
  { k: ['yakup kadri | yaban'], a: "Yakup Kadri Yaban'ın yazarıdır." },
  { k: ['peyami safa | dokuzuncu hariciye | fatih harbiye'], a: "Peyami Safa Dokuzuncu Hariciye Koğuşu ve Fatih-Harbiye'nin yazarıdır." },
  { k: ['sabahattin ali | kurk mantolu madonna | kuyucakli yusuf'], a: "Sabahattin Ali Kürk Mantolu Madonna ve Kuyucaklı Yusuf'un yazarıdır." },
  { k: ['orhan kemal | 72 kogus | eskici'], a: "Orhan Kemal 72. Koğuş'un yazarıdır." },
  { k: ['yasar kemal | ince memed'], a: "Yaşar Kemal İnce Memed'in yazarıdır." },
  { k: ['aziz nesin | mizah'], a: "Aziz Nesin ünlü mizah yazarıdır." },
  { k: ['rifat ilgaz | hababam sinifi'], a: "Rıfat Ilgaz Hababam Sınıfı'nın yazarıdır." },
  { k: ['oguz atay | tutunamayanlar'], a: "Oğuz Atay Tutunamayanlar'ın yazarıdır." },
  { k: ['sait faik | semaver | hikaye'], a: "Sait Faik öyküleriyle ünlüdür." },
  { k: ['necip fazil | kaldirimlar | cile'], a: "Necip Fazıl Kaldırımlar ve Çile'nin şairidir." },
  { k: ['cahit sitki | otuz bes yas'], a: "Cahit Sıtkı Otuz Beş Yaş şiiriyle ünlüdür." },
  { k: ['orhan veli | garip | istanbul dinliyorum'], a: "Orhan Veli Garip akımının öncüsüdür." },
  { k: ['yahya kemal | sessiz gemi | akinclar'], a: "Yahya Kemal Sessiz Gemi'nin şairidir." },
  { k: ['tevfik fikret | haluk defteri | sis'], a: "Tevfik Fikret Sis ve Haluk'un Defteri'nin şairidir." },
  { k: ['namik kemal | vatan silistre'], a: "Namık Kemal Vatan Yahut Silistre'nin yazarıdır." },
  { k: ['sinasi | sair evlenmesi | ilk tiyatro'], a: "Şinasi ilk Türkçe tiyatro Şair Evlenmesi'ni yazdı." },
  { k: ['recaizade | araba sevdasi'], a: "Recaizade Araba Sevdası'nın yazarıdır." },
  { k: ['halit ziya | ask memnu | mai siyah'], a: "Halit Ziya Aşk-ı Memnu'nun yazarıdır." },
  { k: ['mehmet rauf | eylul roman'], a: "Mehmet Rauf Eylül romanının yazarıdır." },
  { k: ['ziya gokalp | turkculuk esaslari'], a: "Ziya Gökalp Türkçülüğün Esasları'nın yazarıdır." },
  // Dunya
  { k: ['shakespeare | hamlet | romeo juliet'], a: "Shakespeare Hamlet ile Romeo ve Juliet'in yazarıdır." },
  { k: ['dickens | oliver twist | iki sehir'], a: "Dickens Oliver Twist ve İki Şehrin Hikayesi'nin yazarıdır." },
  { k: ['tolstoy | savas baris | anna karenina'], a: "Tolstoy Savaş ve Barış ile Anna Karenina'nın yazarıdır." },
  { k: ['dostoyevski | suc ceza | karamazov'], a: "Dostoyevski Suç ve Ceza'nın yazarıdır." },
  { k: ['victor hugo | sefiller | notre dame'], a: "Victor Hugo Sefiller'in yazarıdır." },
  { k: ['goethe | faust | genc werther'], a: "Goethe Faust'un yazarıdır." },
  { k: ['kafka | donusum | dava'], a: "Kafka Dönüşüm ve Dava'nın yazarıdır." },
  { k: ['hemingway | yasli adam deniz'], a: "Hemingway Yaşlı Adam ve Deniz'in yazarıdır." },
  { k: ['steinbeck | fareler insanlar | gazap uzumu'], a: "Steinbeck Fareler ve İnsanlar'ın yazarıdır." },
  { k: ['orwell | 1984 | hayvan ciftligi'], a: "Orwell 1984 ve Hayvan Çiftliği'nin yazarıdır." },
  { k: ['kucuk prens | exupery'], a: "Küçük Prens Saint-Exupéry'nin eseridir." },
  { k: ['jules verne | 80 gun | denizler altinda'], a: "Jules Verne 80 Günde Devri Alem'in yazarıdır." },
  { k: ['mark twain | tom sawyer | huckleberry'], a: "Mark Twain Tom Sawyer'ın yazarıdır." },
  { k: ['jack london | beyaz dis | vahset cagrisi'], a: "Jack London Beyaz Diş'in yazarıdır." },
  { k: ['andersen | kibritci kiz | cirkin ordek'], a: "Andersen Kibritçi Kız masalının yazarıdır." },
  { k: ['la fontaine | fabl | agustos bocegi'], a: "La Fontaine fabllarıyla ünlüdür." },
  { k: ['cervantes | don kisot'], a: "Cervantes Don Kişot'un yazarıdır." },
  { k: ['homeros | ilyada | odysseia'], a: "Homeros İlyada ve Odysseia'nın şairidir." },
  { k: ['dante | ilahi komedya'], a: "Dante İlahi Komedya'nın yazarıdır." },
  { k: ['binbir gece | sehrazat'], a: "Binbir Gece Masalları'nı Şehrazat anlatır." },
  { k: ['dede korkut'], a: "Dede Korkut Oğuz destanlarının anlatıcısıdır." },
  { k: ['karacaoglan | kosma'], a: "Karacaoğlan halk şiirinin ünlü ozanıdır." },
  { k: ['pinokyo | collodi'], a: "Pinokyo Collodi'nin eseridir." },
  { k: ['alice harikalar | carroll'], a: "Alice Harikalar Diyarında Carroll'ın eseridir." },
  { k: ['robinson crusoe | defoe'], a: "Robinson Crusoe Defoe'nun eseridir." },
  { k: ['gulliver | swift'], a: "Gulliver'in Gezileri Swift'in eseridir." },
  { k: ['uc silahsor | monte kristo | dumas'], a: "Üç Silahşörler ve Monte Kristo Dumas'nın eserleridir." },
  { k: ['gurur onyargi | austen'], a: "Gurur ve Önyargı Austen'ın eseridir." },
  { k: ['frankenstein | shelley'], a: "Frankenstein Shelley'nin eseridir." },
  { k: ['moby dick | melville'], a: "Moby Dick Melville'in eseridir." },
];
module.exports = NEW_ENTRIES;
