// Veritabani genisletme set 56: dunya sinemasi
const NEW_ENTRIES = [
  { k: ['titanic | dicaprio'], a: "Titanic batık gemi dramıdır." },
  { k: ['avatar | pandora'], a: "Avatar Pandora gezegeninde geçer." },
  { k: ['harry potter | hogwarts'], a: "Harry Potter Hogwarts büyücülük okulundadır." },
  { k: ['yuzuklerin efendisi | frodo'], a: "Yüzüklerin Efendisi Frodo'nun yolculuğudur." },
  { k: ['star wars | jedi'], a: "Star Wars Jedi destanıdır." },
  { k: ['matrix | neo kirmizi hap'], a: "Matrix simülasyon filmidir." },
  { k: ['inception | ruya hirsizi'], a: "Inception rüya içinde rüya filmidir." },
  { k: ['interstellar | kara delik film'], a: "Interstellar uzay yolculuğu filmidir." },
  { k: ['joker | gotham'], a: "Joker Gotham'ın palyaçosudur." },
  { k: ['parazit | oscar kore'], a: "Parazit Oscarlı Kore filmidir." },
  { k: ['forrest gump | kos'], a: "Forrest Gump koşan saf adamdır." },
  { k: ['gladyator | maximus'], a: "Gladyatör arenada geçer." },
  { k: ['esaretin bedeli | shawshank'], a: "Esaretin Bedeli hapishane dramıdır." },
  { k: ['baba film | godfather'], a: "Baba mafya klasiğidir." },
  { k: ['kara sovalye | batman'], a: "Kara Şövalye Batman filmidir." },
  { k: ['dovus kulubu | tyler'], a: "Dövüş Kulübü kült filmdir." },
  { k: ['yesil yol | john coffey'], a: "Yeşil Yol idam mahkumu dramıdır." },
  { k: ['prestij | sihirbaz rekabet'], a: "Prestij sihirbaz rekabetidir." },
  { k: ['dune | col gezegeni'], a: "Dune çöl gezegeni destanıdır." },
  { k: ['karayip korsanlari | jack'], a: "Karayip Korsanları Jack'le ünlüdür." },
  { k: ['jurassic park | dinozor ada'], a: "Jurassic Park dinozor adasıdır." },
  { k: ['terminator | arnold'], a: "Terminatör robot filmidir." },
  { k: ['rocky | boks filmi'], a: "Rocky boksör hikayesidir." },
  { k: ['james bond | 007'], a: "James Bond 007 ajandır." },
  { k: ['indiana jones | kamci'], a: "Indiana Jones maceracı arkeologdur." },
  { k: ['aslan kral | simba'], a: "Aslan Kral Simba'nın hikayesidir." },
  { k: ['oyuncak hikayesi | woody buzz'], a: "Oyuncak Hikayesi Woody ve Buzz'lıdır." },
  { k: ['shrek | esek'], a: "Shrek dev ve eşek komedisidir." },
  { k: ['buz devri | sid'], a: "Buz Devri mamutlu animasyondur." },
];
module.exports = NEW_ENTRIES;
