// Veritabani genisletme set 19: atasozu anlamlari
const RAW = [
  ['damlaya damlaya gol olur', 'Küçük birikimler zamanla büyür.'],
  ['acele ise seytan karisir', 'Aceleyle yapılan iş bozulur.', ['acele ise karisir']],
  ['sakla samani gelir zamani', 'Önemsiz görünen şey gün gelir lazım olur.'],
  ['ne ekersen onu bicersin', 'Davranışlarının karşılığını görürsün.'],
  ['bir elin nesi var', 'Birlikte çalışmak daha güçlüdür.'],
  ['azi karar cogu zarar', 'Her şeyin fazlası zararlıdır.'],
  ['agac yasken egilir', 'Eğitim küçük yaşta verilir.'],
  ['ak akce kara gun', 'Birikim zor günde kurtarır.'],
  ['armut dibine duser', 'Çocuk ailesine benzer.'],
  ['balik bastan kokar', 'Bozukluk yöneticiden başlar.'],
  ['demir tavinda dovulur', 'Her iş zamanında yapılır.'],
  ['el elden ustundur', 'Her zaman daha iyisi bulunur.'],
  ['gulu seven dikenine katlanir', 'Güzel şeylerin zorluğu olur.'],
  ['igne kendine cuvaldiz baskasina', 'Önce kendini eleştir, sonra başkasını.'],
  ['komsu kulune muhtac', 'Komşu komşuya yeri gelince muhtaç olur.', ['komsu komsunun muhtac', 'komsu komsu kulune']],
  ['korle yatan sasi kalkar', 'Kötü arkadaş insanı bozar.'],
  ['mart kapidan baktirir', 'Mart ayı dengesiz havalar getirir.'],
  ['sabreden dervis muradina ermis', 'Sabreden amacına ulaşır.'],
  ['su uyur dusman uyumaz', 'Tehlikeye karşı uyanık olunur.'],
  ['tatli dil yilani deliginden cikarir', 'Güzel söz her kapıyı açar.'],
  ['uzum uzume kararir', 'İnsan arkadaşına benzer.'],
  ['yalancinin mumu yatsiya kadar', 'Yalan çabuk ortaya çıkar.'],
  ['zararin neresinden donulse kar', 'Hatadan erken dönmek kazançtır.'],
  ['bugunun isini yarina birakma', 'İşler ertelenmeden yapılır.'],
  ['dost kara gunde belli olur', 'Gerçek dost zor günde tanınır.'],
  ['huylu huyundan vazgecmez', 'Alışkanlıklar kolay değişmez.'],
  ['iyilik yap denize at', 'İyilik karşılık beklemeden yapılır.'],
  ['kervan yolda duzulur', 'Eksikler yolda tamamlanır, başlamak gerekir.'],
  ['lafla peynir gemisi yurumez', 'Konuşmakla iş bitmez, çalışmak gerekir.'],
  ['meyve veren agac taslanir', 'Başarılı insan kıskanılır.'],
  ['ne sis yansin ne kebap', 'İki tarafı da kırmadan çözüm bulunur.'],
  ['ofkeyle kalkan zararla oturur', 'Öfkeyle karar veren pişman olur.'],
  ['soz gumusse sukut altindir', 'Bazen susmak konuşmaktan değerlidir.'],
  ['vakit nakittir', 'Zaman paradan değerlidir.'],
  ['tilkinin donup dolasacagi', 'Herkes sonunda ait olduğu yere döner.'],
];
const NEW_ENTRIES = RAW.map(([k, a, x]) => ({ k: [k, k + ' ne demek'].concat(x || []), a }));
module.exports = NEW_ENTRIES;
