// Veritabani genisletme set 4: iller + tarih + genel kultur + pratik
const NEW_ENTRIES = [
  // Iller
  { k: ['izmir | izmir neyi meshur'], a: "İzmir Ege'nin incisidir; saat kulesi, boyozu ve kordonuyla ünlüdür." },
  { k: ['bursa | bursa neyi meshur'], a: "Bursa ilk Osmanlı başkentidir; Uludağ, İskender ve ipeğiyle ünlüdür." },
  { k: ['antalya | antalya neyi meshur'], a: "Antalya Akdeniz'in turizm başkentidir; Konyaaltı ve Düden şelalesiyle ünlüdür." },
  { k: ['adana | adana neyi meshur'], a: "Adana kebabı, şalgamı ve taş köprüsüyle ünlüdür." },
  { k: ['konya | konya neyi meshur'], a: "Konya Mevlana şehri ve etli ekmeğiyle ünlüdür." },
  { k: ['gaziantep | antep neyi meshur'], a: "Gaziantep baklava ve kebaplarıyla gastronomi şehridir." },
  { k: ['trabzon | trabzon neyi meshur'], a: "Trabzon Sümela Manastırı, hamsisi ve horonuyla ünlüdür." },
  { k: ['rize | rize neyi meshur'], a: "Rize çayın başkentidir; Ayder yaylasıyla ünlüdür." },
  { k: ['erzurum | erzurum neyi meshur'], a: "Erzurum cağ kebabı, kadayıf dolması ve Palandöken kayağıyla ünlüdür." },
  { k: ['kayseri | kayseri neyi meshur'], a: "Kayseri mantısı, pastırması ve Erciyes dağıyla ünlüdür." },
  { k: ['eskisehir | odunpazari'], a: "Eskişehir porsuğu, Odunpazarı evleri ve çiğ böreğiyle ünlüdür." },
  { k: ['mugla | bodrum | marmaris'], a: "Muğla Bodrum ve Marmaris gibi tatil beldeleriyle ünlüdür." },
  { k: ['denizli | pamukkale'], a: "Denizli Pamukkale travertenleri ve horozuyla ünlüdür." },
  { k: ['nevsehir | kapadokya | peri bacalari'], a: "Nevşehir Kapadokya peri bacaları ve balon turlarıyla ünlüdür." },
  { k: ['sanliurfa | balikli gol'], a: "Şanlıurfa Balıklıgöl ve çiğ köftesiyle peygamberler şehridir." },
  { k: ['mardin | mardin evleri'], a: "Mardin taş evleri ve Süryani kültürüyle açık hava müzesidir." },
  { k: ['diyarbakir | diyarbakir surlari'], a: "Diyarbakır surları ve karpuzuyla ünlüdür." },
  { k: ['van golu | akdamar'], a: "Van Gölü Türkiye'nin en büyük gölüdür; Akdamar kilisesiyle ünlüdür." },
  { k: ['samsun | bandirma vapuru | 19 mayis'], a: "Samsun 19 Mayıs 1919'da Atatürk'ün Bandırma Vapuru'yla ayak bastığı şehirdir." },
  { k: ['edirne | selimiye camii'], a: "Edirne Selimiye Camii ve tarihi Kırkpınar güreşleriyle ünlüdür." },
  { k: ['hatay | antakya | mozaik muzesi'], a: "Hatay mozaikleri, künefesi ve medeniyetler sofrasıyla ünlüdür." },
  { k: ['kars | ani harabeleri | kars kasari'], a: "Kars Ani harabeleri, kaşarı ve Sarıkamış kayağıyla ünlüdür." },
  { k: ['mersin | kizkalesi'], a: "Mersin Kızkalesi, tantunisi ve narenciyesiyle ünlüdür." },
  { k: ['aydin | afrodisias'], a: "Aydın inciri ve Afrodisias antik kentiyle ünlüdür." },
  // Tarih
  { k: ['malazgirt | 1071'], a: "Malazgirt Zaferi 1071'de Alparslan komutasında kazanıldı, Anadolu'nun kapısı açıldı." },
  { k: ['cumhuriyet ne zaman | 29 ekim 1923'], a: "Cumhuriyet 29 Ekim 1923'te ilan edildi." },
  { k: ['tbmm ne zaman acildi | 23 nisan 1920'], a: "TBMM 23 Nisan 1920'de Ankara'da açıldı." },
  { k: ['lozan | lozan antlasmasi'], a: "Lozan Antlaşması 1923'te imzalandı, Türkiye'nin bağımsızlığı tanındı." },
  { k: ['mondros | mondros ateskesi'], a: "Mondros Ateşkesi 1918'de imzalandı, Osmanlı fiilen sona erdi." },
  { k: ['harf devrimi | latin alfabesi'], a: "Harf Devrimi 1928'de yapıldı, Latin alfabesine geçildi." },
  { k: ['saltanat ne zaman kaldirildi | 1922'], a: "Saltanat 1 Kasım 1922'de kaldırıldı." },
  { k: ['sivas kongresi | erzurum kongresi | amasya genelgesi'], a: "Amasya Genelgesi, Erzurum ve Sivas kongreleri 1919'da Kurtuluş'un yol haritası oldu." },
  { k: ['mudanya | mudanya ateskesi'], a: "Mudanya Ateşkesi 1922'de imzalandı, Kurtuluş Savaşı fiilen bitti." },
  { k: ['ataturk ne zaman oldu | 10 kasim 1938'], a: "Atatürk 10 Kasım 1938'de Dolmabahçe'de vefat etti." },
  { k: ['canakkale savasi ne zaman | 1915'], a: "Çanakkale Savaşı 1915'te oldu, 18 Mart deniz zaferiyle anılır." },
  // Genel kultur
  { k: ['kitalar | kac kita var | 7 kita'], a: "7 kıta vardır: Asya, Afrika, Avrupa, Kuzey ve Güney Amerika, Okyanusya, Antarktika." },
  { k: ['okyanuslar | kac okyanus var'], a: "5 okyanus vardır: Büyük (Pasifik), Atlas, Hint, Güney ve Arktik." },
  { k: ['en buyuk okyanus | pasifik'], a: "En büyük okyanus Büyük Okyanus'tur (Pasifik)." },
  { k: ['en buyuk col | sahra'], a: "En büyük sıcak çöl Sahra'dır." },
  { k: ['en derin nokta | mariana'], a: "En derin nokta Mariana Çukuru'dur, yaklaşık 11 kilometre." },
  { k: ['en uzun nehir | nil'], a: "En uzun nehir genelde Nil kabul edilir, Amazon da adaydır." },
  { k: ['fotosentez'], a: "Fotosentez bitkilerin güneş ışığıyla besin üretmesidir." },
  { k: ['yercekimi | newton elma'], a: "Yerçekimini Newton açıkladı; elma hikayesiyle anılır." },
  { k: ['izafiyet | einstein'], a: "İzafiyet teorisini Einstein kurdu; E=mc² formülüyle ünlüdür." },
  { k: ['big bang | buyuk patlama'], a: "Büyük Patlama evrenin yaklaşık 13,8 milyar yıl önceki başlangıcıdır." },
  { k: ['dinozor | dinozorlar ne zaman'], a: "Dinozorlar yaklaşık 66 milyon yıl önce yok oldu." },
  { k: ['insan kac kemik | 206 kemik'], a: "Yetişkin insanda 206 kemik vardır." },
  { k: ['kan gruplari | 0 a b ab'], a: "4 ana kan grubu vardır: 0, A, B ve AB (Rh +/- ile 8'e çıkar)." },
  { k: ['deprem siddeti | richter'], a: "Deprem büyüklüğü Richter gibi ölçeklerle ölçülür; her 1 birim ~32 kat enerjidir." },
  { k: ['tsunami'], a: "Tsunami denizaltı depremlerinin yarattığı dev dalgalardır." },
  { k: ['ekvator'], a: "Ekvator Dünya'yı iki yarımküreye bölen hayali çizgidir." },
  { k: ['kuzey kutbu | guney kutbu'], a: "Kuzey Kutbu buz denizidir, Güney Kutbu Antarktika kıtasıdır." },
  { k: ['olimpiyat | 4 yilda bir'], a: "Olimpiyatlar 4 yılda bir yapılır, modern başlangıcı 1896 Atina'dır." },
  { k: ['dunya kupasi | fifa'], a: "Dünya Kupası 4 yılda bir yapılır." },
  { k: ['nobel | nobel odulu'], a: "Nobel Ödülleri bilim, edebiyat ve barış alanlarında verilir." },
  { k: ['mimar sinan | suleymaniye | selimiye mimari'], a: "Mimar Sinan Süleymaniye ve Selimiye'nin mimarıdır." },
  { k: ['piri reis | ilk dunya haritasi'], a: "Piri Reis ünlü denizci ve haritacıdır, dünya haritasıyla tanınır." },
  { k: ['evliya celebi | seyahatname'], a: "Evliya Çelebi Seyahatname'nin yazarı ünlü gezgindir." },
  { k: ['ibni sina | avicenna tip'], a: "İbni Sina Tıp Kanunu'yla tanınan ünlü hekim ve bilgindir." },
  { k: ['nazim hikmet'], a: "Nazım Hikmet serbest şiirin öncüsü ünlü şairdir." },
  { k: ['mevlana | mesnevi | konya'], a: "Mevlana Mesnevi'nin yazarı, hoşgörüyle anılan mutasavvıftır." },
  { k: ['kanuni | muhtesem yuzyil padisah'], a: "Kanuni Sultan Süleyman 46 yıl tahtta kalan Osmanlı padişahıdır." },
  // Pratik
  { k: ['turkiye telefon kodu | +90'], a: "Türkiye'nin telefon kodu +90'dır." },
  { k: ['112 ne | acil numara'], a: "112 tüm acil durumların (ambulans, itfaiye, polis) tek numarasıdır." },
  { k: ['burun kanamasi | burun kaniyor'], a: "Burun kanamasında başı hafif öne eğ, burun kanatlarını 10 dakika sık. Durmazsa doktora git." },
  { k: ['yanik ilk yardim | elim yandi'], a: "Yanığa ilk iş soğuk su tut (10-15 dk). Buz ve diş macunu sürme, su toplarsa patlatma." },
  { k: ['ari sokmasi | ari soktu'], a: "Arı sokmasında iğneyi kartla sıyır, soğuk uygula. Nefes darlığı olursa hemen 112'yi ara." },
  { k: ['bayilma ilk yardim | bayildi'], a: "Bayılmada kişiyi sırtüstü yatır, ayaklarını yükselt, hava almasını sağla. Ayılmazsa 112." },
  { k: ['mevsimler | ilkbahar yaz sonbahar kis'], a: "4 mevsim vardır: ilkbahar, yaz, sonbahar, kış." },
  { k: ['resmi tatil | dini bayram | milli bayram'], a: "Resmi tatiller: 23 Nisan, 19 Mayıs, 30 Ağustos, 29 Ekim ve dini bayramlardır." },
  { k: ['bayrak anlami | turk bayragi'], a: "Türk bayrağındaki hilal ve yıldız bağımsızlığın simgesidir." },
  { k: ['elektrik voltaj | 220 volt'], a: "Türkiye'de şebeke elektriği 220 volttur." },
];
module.exports = NEW_ENTRIES;
