// Veritabani genisletme set 6: kara hayvanlari
const NEW_ENTRIES = [
  { k: ['kaplan | bengal kaplani'], a: "Kaplan en büyük kedi türüdür, çizgileri parmak izi gibi her bireyde farklıdır." },
  { k: ['zebra'], a: "Zebra çizgili at benzeri hayvandır, çizgileri sineklerden korur." },
  { k: ['leopar | pars'], a: "Leopar ağaca tırmanabilen benekli büyük kedidir." },
  { k: ['gergedan'], a: "Gergedan kalın derili, boynuzlu iri hayvandır." },
  { k: ['su aygiri | hipopotam'], a: "Su aygırı günün çoğunu suda geçiren iri hayvandır." },
  { k: ['deve | hoduk'], a: "Deve hörgücünde yağ depolar, çölde susuzluğa dayanır." },
  { k: ['kurt | bozkurt'], a: "Kurt sürü halinde avlanan yabani köpekgildir." },
  { k: ['tilki | kurnaz tilki'], a: "Tilki kurnazlığıyla ünlü küçük yabani köpekgildir." },
  { k: ['cakal'], a: "Çakal kurttan küçük, gece avlanan yabani köpekgildir." },
  { k: ['sirtlan'], a: "Sırtlan güçlü çenesiyle kemik bile kırar." },
  { k: ['ayi | bozayi'], a: "Bozayı kışın kış uykusuna yatan iri hayvandır." },
  { k: ['yarasa | vampir yarasa'], a: "Yarasa uçabilen tek memelidir, gece böcek avlar." },
  { k: ['sincap'], a: "Sincap kış için fındık saklayan kemirgendir." },
  { k: ['tavsan | ada tavşanı'], a: "Tavşan uzun kulaklı, hızlı üreyen kemirgendir." },
  { k: ['kirpi'], a: "Kirpi dikenli küçük hayvandır, tehlike anında top olur." },
  { k: ['kostebek'], a: "Köstebek toprağı kazar, gözleri neredeyse görmez." },
  { k: ['fare | sican'], a: "Fare hızlı üreyen küçük kemirgendir." },
  { k: ['maymun | şempanze | sempanze'], a: "Şempanze insana en yakın hayvanlardan biridir, alet kullanır." },
  { k: ['goril'], a: "Goril en büyük primattır, otçuldur." },
  { k: ['kanguru'], a: "Kanguru yavrusunu kesesinde taşır, Avustralya'nın simgesidir." },
  { k: ['koala'], a: "Koala okaliptüs yaprağı yiyen Avustralya hayvanıdır." },
  { k: ['bukalemun'], a: "Bukalemun renk değiştiren, dili hızlı uzayan sürüngendir." },
  { k: ['kertenkele | geko'], a: "Kertenkele kuyruğunu bırakıp kaçabilen sürüngendir." },
  { k: ['kurbaga'], a: "Kurbağa hem suda hem karada yaşar, sinek avlar." },
  { k: ['yilan zehirli | engerek'], a: "Engerek Türkiye'deki zehirli yılanlardandır; ısırırsa hemen 112 aranır." },
  { k: ['timsah | nil timsahi'], a: "Timsah güçlü çeneli su sürüngenidir." },
  { k: ['kaplumbaga | tosbağa | tosbaga'], a: "Kaplumbağa kabuğuyla korunan yavaş sürüngendir." },
  { k: ['at | yilki ati'], a: "At insanlık tarihinin en eski binek hayvanıdır." },
  { k: ['esek | katir fark'], a: "Katır at ile eşeğin yavrusudur, dayanıklıdır." },
  { k: ['inek | sigir'], a: "İnek süt veren büyükbaş hayvandır." },
  { k: ['koyun | kuzu'], a: "Koyun yünü ve sütü için beslenir, yavrusu kuzudur." },
  { k: ['keci | oğlak | oglak'], a: "Keçi dik yamaçlara tırmanabilen küçükbaş hayvandır." },
  { k: ['tavuk | horoz | civciv'], a: "Tavuk yumurta verir, erkeği horoz, yavrusu civcivdir." },
  { k: ['ordek'], a: "Ördek perdeli ayaklı su kuşudur." },
  { k: ['kaz'], a: "Kaz gagalı, göç eden iri su kuşudur." },
  { k: ['domuz | yaban domuzu'], a: "Yaban domuzu ormanda yaşayan güçlü hayvandır." },
];
module.exports = NEW_ENTRIES;
