// Veritabani genisletme set 1: baskentler + para birimleri
// Calistir: node expand-db.js (tum expand-*.js dosyalarini sirayla okur)
const NEW_ENTRIES = [
  { k: ['kanada baskenti | ottava', 'ottava'], a: "Kanada'nın başkenti Ottava'dır." },
  { k: ['avustralya baskenti | kanberra', 'kanberra'], a: "Avustralya'nın başkenti Kanberra'dır." },
  { k: ['brezilya baskenti | brasilya', 'brasilya'], a: "Brezilya'nın başkenti Brasílya'dır." },
  { k: ['arjantin baskenti | buenos aires'], a: "Arjantin'in başkenti Buenos Aires'tir." },
  { k: ['meksika baskenti | mexico city'], a: "Meksika'nın başkenti Meksiko'dur." },
  { k: ['japonya baskenti | tokyo'], a: "Japonya'nın başkenti Tokyo'dur." },
  { k: ['cin baskenti | pekin'], a: "Çin'in başkenti Pekin'dir." },
  { k: ['hindistan baskenti | yeni delhi'], a: "Hindistan'ın başkenti Yeni Delhi'dir." },
  { k: ['misir baskenti | kahire'], a: "Mısır'ın başkenti Kahire'dir." },
  { k: ['nijerya baskenti | abuca', 'abuca'], a: "Nijerya'nın başkenti Abuja'dır." },
  { k: ['kenya baskenti | nairobi'], a: "Kenya'nın başkenti Nairobi'dir." },
  { k: ['suudi arabistan baskenti | riyad'], a: "Suudi Arabistan'ın başkenti Riyad'dır." },
  { k: ['iran baskenti | tahran'], a: "İran'ın başkenti Tahran'dır." },
  { k: ['irak baskenti | bagdat'], a: "Irak'ın başkenti Bağdat'tır." },
  { k: ['yunanistan baskenti | atina'], a: "Yunanistan'ın başkenti Atina'dır." },
  { k: ['bulgaristan baskenti | sofya'], a: "Bulgaristan'ın başkenti Sofya'dır." },
  { k: ['romanya baskenti | bukres'], a: "Romanya'nın başkenti Bükreş'tir." },
  { k: ['macaristan baskenti | budapeste'], a: "Macaristan'ın başkenti Budapeşte'dir." },
  { k: ['polonya baskenti | varsova'], a: "Polonya'nın başkenti Varşova'dır." },
  { k: ['ukrayna baskenti | kiev'], a: "Ukrayna'nın başkenti Kiev'dir." },
  { k: ['isvec baskenti | stokholm', 'stokholm'], a: "İsveç'in başkenti Stokholm'dür." },
  { k: ['norvec baskenti | oslo'], a: "Norveç'in başkenti Oslo'dur." },
  { k: ['finlandiya baskenti | helsinki'], a: "Finlandiya'nın başkenti Helsinki'dir." },
  { k: ['danimarka baskenti | kopenhag'], a: "Danimarka'nın başkenti Kopenhag'dır." },
  { k: ['hollanda baskenti | amsterdam'], a: "Hollanda'nın başkenti Amsterdam'dır." },
  { k: ['belcika baskenti | bruksel'], a: "Belçika'nın başkenti Brüksel'dir." },
  { k: ['isvicre baskenti | bern'], a: "İsviçre'nin başkenti Bern'dir." },
  { k: ['portekiz baskenti | lizbon'], a: "Portekiz'in başkenti Lizbon'dur." },
  { k: ['ispanya baskenti | madrid'], a: "İspanya'nın başkenti Madrid'dir." },
  { k: ['italya baskenti | roma'], a: "İtalya'nın başkenti Roma'dır." },
  { k: ['ingiltere baskenti | londra'], a: "İngiltere'nin başkenti Londra'dır." },
  { k: ['irlanda baskenti | dublin'], a: "İrlanda'nın başkenti Dublin'dir." },
  { k: ['izlanda baskenti | reykjavik'], a: "İzlanda'nın başkenti Reykjavik'tir." },
  { k: ['kazakistan baskenti | astana'], a: "Kazakistan'ın başkenti Astana'dır." },
  { k: ['ozbekistan baskenti | taskent'], a: "Özbekistan'ın başkenti Taşkent'tir." },
  { k: ['azerbaycan baskenti | baku'], a: "Azerbaycan'ın başkenti Bakü'dür." },
  { k: ['gurcistan baskenti | tiflis'], a: "Gürcistan'ın başkenti Tiflis'tir." },
  { k: ['ermenistan baskenti | erivan'], a: "Ermenistan'ın başkenti Erivan'dır." },
  { k: ['pakistan baskenti | islamabad'], a: "Pakistan'ın başkenti İslamabad'dır." },
  { k: ['endonezya baskenti | cakarta'], a: "Endonezya'nın başkenti Cakarta'dır." },
  { k: ['malezya baskenti | kuala lumpur'], a: "Malezya'nın başkenti Kuala Lumpur'dur." },
  { k: ['tayland baskenti | bangkok'], a: "Tayland'ın başkenti Bangkok'tur." },
  { k: ['vietnam baskenti | hanoi'], a: "Vietnam'ın başkenti Hanoi'dir." },
  { k: ['guney kore baskenti | seul'], a: "Güney Kore'nin başkenti Seul'dür." },
  { k: ['kuba baskenti | havana'], a: "Küba'nın başkenti Havana'dır." },
  { k: ['sili baskenti | santiago'], a: "Şili'nin başkenti Santiago'dur." },
  { k: ['peru baskenti | lima'], a: "Peru'nun başkenti Lima'dır." },
  { k: ['kolombiya baskenti | bogota'], a: "Kolombiya'nın başkenti Bogotá'dır." },
  { k: ['venezuela baskenti | karakas'], a: "Venezuela'nın başkenti Karakas'tır." },
  { k: ['fas baskenti | rabat'], a: "Fas'ın başkenti Rabat'tır." },
  { k: ['cezayir baskenti | cezayir'], a: "Cezayir'in başkenti Cezayir'dir." },
  { k: ['tunus baskenti | tunus'], a: "Tunus'un başkenti Tunus'tur." },
  { k: ['libya baskenti | trablus'], a: "Libya'nın başkenti Trablus'tur." },
  { k: ['etiyopya baskenti | addis ababa'], a: "Etiyopya'nın başkenti Addis Ababa'dır." },
  { k: ['yeni zelanda baskenti | vellington', 'vellington'], a: "Yeni Zelanda'nın başkenti Wellington'dur." },
  { k: ['filipinler baskenti | manila'], a: "Filipinler'in başkenti Manila'dır." },
  // Para birimleri
  { k: ['abd para birimi | amerikan dolari', 'dolar hangi ulke'], a: "ABD'nin para birimi Amerikan dolarıdır." },
  { k: ['avrupa para birimi | euro hangi ulke'], a: "Avrupa Birliği'nin ortak para birimi eurodur." },
  { k: ['ingiltere para birimi | sterlin'], a: "İngiltere'nin para birimi sterlindir." },
  { k: ['japonya para birimi | yen'], a: "Japonya'nın para birimi yendir." },
  { k: ['isvicre para birimi | frank', 'isvicre frangi'], a: "İsviçre'nin para birimi franktır." },
  { k: ['cin para birimi | yuan'], a: "Çin'in para birimi yuandır." },
  { k: ['rusya para birimi | ruble'], a: "Rusya'nın para birimi rubledir." },
  { k: ['hindistan para birimi | rupi'], a: "Hindistan'ın para birimi rupidir." },
  { k: ['brezilya para birimi | real'], a: "Brezilya'nın para birimi realdir." },
  { k: ['kanada para birimi | kanada dolari'], a: "Kanada'nın para birimi Kanada dolarıdır." },
  { k: ['avustralya para birimi | avustralya dolari'], a: "Avustralya'nın para birimi Avustralya dolarıdır." },
  { k: ['guney kore para birimi | von', 'won'], a: "Güney Kore'nin para birimi wondur." },
  { k: ['turkiye para birimi | turk lirasi'], a: "Türkiye'nin para birimi Türk lirasıdır." },
  { k: ['suudi arabistan para birimi | riyal'], a: "Suudi Arabistan'ın para birimi riyaldir." },
  { k: ['bae para birimi | dirhem'], a: "Birleşik Arap Emirlikleri'nin para birimi dirhemdir." },
  { k: ['isvec para birimi | isvec kronu', 'kron hangi ulke'], a: "İsveç'in para birimi kronudur." },
  { k: ['norvec para birimi | norvec kronu'], a: "Norveç'in para birimi kronudur." },
  { k: ['danimarka para birimi | danimarka kronu'], a: "Danimarka'nın para birimi kronudur." },
  { k: ['polonya para birimi | zloti'], a: "Polonya'nın para birimi zlotidir." },
  { k: ['macaristan para birimi | forint'], a: "Macaristan'ın para birimi forinttir." },
  { k: ['cekya para birimi | cek kronu'], a: "Çekya'nın para birimi kronudur." },
  { k: ['ukrayna para birimi | grivna'], a: "Ukrayna'nın para birimi grivnadır." },
  { k: ['meksika para birimi | pezo', 'meksika pezosu'], a: "Meksika'nın para birimi pezodur." },
];
module.exports = NEW_ENTRIES;
