// Sozluk genisletme: eksik temel kelimeler
const NEW_PAIRS = [
  ['butterfly', 'kelebek'], ['shadow', 'gölge'], ['bridge', 'köprü'],
  ['thunder', 'gök gürültüsü'], ['earthquake', 'deprem'], ['seed', 'tohum'],
  ['salt', 'tuz'], ['sugar', 'şeker'], ['room', 'oda'], ['bed', 'yatak'],
  ['mirror', 'ayna'], ['clock', 'saat'], ['market', 'pazar'], ['shop', 'dükkan'],
  ['street', 'sokak'], ['health', 'sağlık'], ['old', 'yaşlı'],
  ['cloud', 'bulut'], ['rain', 'yağmur'], ['snow', 'kar'], ['wind', 'rüzgar'],
  ['storm', 'fırtına'], ['star', 'yıldız'], ['moon', 'ay'], ['sun', 'güneş'],
  ['mountain', 'dağ'], ['river', 'nehir'], ['forest', 'orman'], ['desert', 'çöl'],
  ['island', 'ada'], ['ocean', 'okyanus'], ['valley', 'vadi'], ['hill', 'tepe'],
  ['flower', 'çiçek'], ['tree', 'ağaç'], ['grass', 'ot'], ['leaf', 'yaprak'],
  ['root', 'kök'], ['garden', 'bahçe'], ['window', 'pencere'], ['door', 'kapı'],
  ['key', 'anahtar'], ['house', 'ev'], ['kitchen', 'mutfak'], ['table', 'masa'],
  ['chair', 'sandalye'], ['phone', 'telefon'], ['computer', 'bilgisayar'],
  ['money', 'para'], ['car', 'araba'], ['bus', 'otobüs'], ['train', 'tren'],
  ['plane', 'uçak'], ['ship', 'gemi'], ['bicycle', 'bisiklet'],
  ['doctor', 'doktor'], ['hospital', 'hastane'], ['medicine', 'ilaç'],
  ['family', 'aile'], ['friend', 'arkadaş'], ['love', 'sevgi'],
  ['happy', 'mutlu'], ['sad', 'üzgün'], ['angry', 'kızgın'], ['tired', 'yorgun'],
  ['hungry', 'aç'], ['thirsty', 'susamış'], ['hot', 'sıcak'], ['cold', 'soğuk'],
  ['big', 'büyük'], ['small', 'küçük'], ['long', 'uzun'], ['short', 'kısa'],
  ['new', 'yeni'], ['fast', 'hızlı'], ['slow', 'yavaş'], ['strong', 'güçlü'],
  ['weak', 'zayıf'], ['rich', 'zengin'], ['poor', 'fakir'], ['clean', 'temiz'],
  ['dirty', 'kirli'], ['easy', 'kolay'], ['hard', 'zor'],
  ['beautiful', 'güzel'], ['ugly', 'çirkin'], ['bread', 'ekmek'], ['milk', 'süt'],
  ['egg', 'yumurta'], ['cheese', 'peynir'], ['honey', 'bal'], ['water', 'su'],
  ['book', 'kitap'], ['pen', 'kalem'], ['school', 'okul'], ['teacher', 'öğretmen'],
  ['student', 'öğrenci'], ['lesson', 'ders'], ['exam', 'sınav'],
];
module.exports = NEW_PAIRS;
