// Veritabani genisletme set 21: turistik yerler
const NEW_ENTRIES = [
  { k: ['efes | artemis tapinagi | celsus'], a: "Efes Celsus Kütüphanesi ve Artemis Tapınağı ile ünlü antik kenttir." },
  { k: ['bergama | asklepion'], a: "Bergama Asklepion sağlık merkeziyle ünlüdür." },
  { k: ['tarihi yerler troya | truva ati'], a: "Troya destanlara konu olan antik kenttir." },
  { k: ['gobeklitepe | ilk tapinak'], a: "Göbeklitepe bilinen en eski tapınaktır." },
  { k: ['nemrut | tanri heykelleri'], a: "Nemrut dev tanrı heykelleriyle ünlüdür." },
  { k: ['catalhoyuk | ilk sehir'], a: "Çatalhöyük bilinen en eski yerleşimlerdendir." },
  { k: ['hattusas | hitit baskenti'], a: "Hattuşaş Hititlerin başkentiydi." },
  { k: ['aspendos | tiyatro'], a: "Aspendos en sağlam Roma tiyatrosuna sahiptir." },
  { k: ['side | apollo tapinagi'], a: "Side Apollon Tapınağı ve tiyatrosuyla ünlüdür." },
  { k: ['olu deniz | fethiye | kelebekler vadisi'], a: "Ölüdeniz ve Kelebekler Vadisi Fethiye'nin ünlü koylarıdır." },
  { k: ['kas | kalkan | kekova'], a: "Kaş, Kalkan ve Kekova dalış ve tekne turlarıyla ünlüdür." },
  { k: ['alanya kalesi | dim cayi'], a: "Alanya Kalesi ve Dim Çayı ile ünlüdür." },
  { k: ['datca | ayvalik | bozcaada'], a: "Datça, Ayvalık ve Bozcaada sakin tatil beldeleridir." },
  { k: ['sirince | cumalikizik | safranbolu'], a: "Şirince, Cumalıkızık ve Safranbolu tarihi köylerdir." },
  { k: ['amasra | yedigoller'], a: "Amasra sahili, Yedigöller sonbahar renkleriyle ünlüdür." },
  { k: ['saklikent | ihlara vadisi'], a: "Saklıkent kanyon, Ihlara vadi yürüyüşüyle ünlüdür." },
  { k: ['patara | olympos | phaselis'], a: "Patara, Olympos ve Phaselis Antalya'nın antik kıyılarıdır." },
  { k: ['likya yolu | frig vadisi'], a: "Likya Yolu ve Frig Vadisi ünlü yürüyüş rotalarıdır." },
  { k: ['divrigi ulu camii | sultan hani'], a: "Divriği Ulu Camii taş işçiliğiyle UNESCO'dadır." },
  { k: ['cifte minare | yakutiye | uc kumbet'], a: "Çifte Minare, Yakutiye ve Üç Kümbetler Erzurum'un simgeleridir." },
  { k: ['tortum selalesi | manavgat'], a: "Tortum ve Manavgat ünlü şelalelerdir." },
  { k: ['ishak pasa | van kalesi'], a: "İshak Paşa Sarayı ve Van Kalesi doğunun simgeleridir." },
  { k: ['hasankeyf | zerzevan'], a: "Hasankeyf Ilısu barajıyla taşınan tarihtir." },
  { k: ['demre noel baba | myra'], a: "Demre Noel Baba kilisesi ve Myra ile ünlüdür." },
  { k: ['paris eyfel | louvre | paris meshur'], a: "Paris Eyfel Kulesi ve Louvre ile ünlüdür." },
  { k: ['londra big ben | tower'], a: "Londra Big Ben ve Tower Köprüsü ile ünlüdür." },
  { k: ['roma kolezyum | vatikan'], a: "Roma Kolezyum ve Vatikan ile ünlüdür." },
  { k: ['barselona sagrada | gaudi'], a: "Barselona Gaudi eserleri ve Sagrada Familia ile ünlüdür." },
  { k: ['venedik | gondola | san marco'], a: "Venedik kanalları ve gondollarıyla ünlüdür." },
  { k: ['prag | karl koprusu'], a: "Prag Karl Köprüsü ve eski şehriyle ünlüdür." },
  { k: ['dubai burc halife | palmiye'], a: "Dubai Burç Halife ve palmiye adalarıyla ünlüdür." },
  { k: ['new york ozgurluk | times'], a: "New York Özgürlük Heykeli ve Times Meydanı ile ünlüdür." },
  { k: ['bali | maldivler | santorini'], a: "Bali, Maldivler ve Santorini ünlü tatil adalarıdır." },
];
module.exports = NEW_ENTRIES;
