// Veritabani genisletme set 17: din kulturu + dunya tarihi
const NEW_ENTRIES = [
  { k: ['hz muhammed dogum | 571 mekke'], a: "Hz. Muhammed 571'de Mekke'de doğdu." },
  { k: ['hicret | 622 medine'], a: "Hicret 622'de Mekke'den Medine'ye göctür." },
  { k: ['dort halife | hulefa'], a: "Dört halife sırasıyla: Ebubekir, Ömer, Osman ve Ali'dir." },
  { k: ['kadir gecesi | ramazan ayi'], a: "Kadir Gecesi ramazan ayı içindedir." },
  { k: ['kurban bayrami | hac'], a: "Kurban Bayramı hac mevsiminde kutlanır." },
  { k: ['roma imparatorlugu | sezari'], a: "Roma İmparatorluğu antik çağın en büyük devletiydi." },
  { k: ['bizans | dogu roma | konstantinopolis'], a: "Bizans başkenti Konstantinopolis olan Doğu Roma'dır." },
  { k: ['fransiz ihtilali | 1789'], a: "Fransız İhtilali 1789'da oldu." },
  { k: ['sanayi devrimi | buhar makinesi'], a: "Sanayi Devrimi buhar makinesiyle İngiltere'de başladı." },
  { k: ['soguk savas | iki kutup'], a: "Soğuk Savaş ABD ile SSCB arasındaki gerginlik dönemiydi." },
  { k: ['berlin duvari | 1989 yikilis'], a: "Berlin Duvarı 1989'da yıkıldı." },
  { k: ['ronesans | reform'], a: "Rönesans sanat ve bilimde yeniden doğuş dönemidir." },
  { k: ['ankara savasi | 1402 fetret'], a: "Ankara Savaşı 1402'de oldu, Fetret Devri başladı." },
  { k: ['caldiran | 1514'], a: "Çaldıran 1514'te Safevilere karşı kazanıldı." },
  { k: ['preveze | barbaros 1538'], a: "Preveze 1538'de Barbaros komutasında kazanıldı." },
  { k: ['inebahti | 1571'], a: "İnebahtı 1571'de donanmamız yenildi." },
  { k: ['viyana kusatmasi | 1683 Merzifonlu'], a: "II. Viyana Kuşatması 1683'te başarısız oldu." },
  { k: ['karlofca | 1699 ilk toprak kaybi'], a: "Karlofça 1699'da ilk büyük toprak kaybımızdır." },
  { k: ['kucuk kaynarca | 1774 kirim'], a: "Küçük Kaynarca 1774'te Kırım elden çıktı." },
  { k: ['tanzimat | 1839 gulhane'], a: "Tanzimat 1839 Gülhane Hattı'yla ilan edildi." },
  { k: ['islahat fermani | 1856'], a: "Islahat Fermanı 1856'da ilan edildi." },
  { k: ['mesrutiyet | 1876 1908'], a: "I. Meşrutiyet 1876, II. Meşrutiyet 1908'de ilan edildi." },
  { k: ['trablusgarp | 1911 libya'], a: "Trablusgarp Savaşı 1911'de İtalya'ya karşı yapıldı." },
  { k: ['balkan savaslari | 1912'], a: "Balkan Savaşları 1912-13'te oldu." },
  { k: ['sarıkamis | 1914 donma'], a: "Sarıkamış 1914'te ağır kış koşullarında kayıpla sonuçlandı." },
  { k: ["kutul amare | 1916 halil pasa"], a: "Kut'ül Amare 1916'da İngilizlere karşı kazanıldı." },
];
module.exports = NEW_ENTRIES;
