// Veritabani genisletme set 7: deniz + kus + bocek + bitki
const NEW_ENTRIES = [
  // Deniz
  { k: ['kopekbaligi | beyaz kopekbaligi'], a: "Köpekbalığı kıkırdaklı yırtıcı balıktır, kokuyu kilometrelerce öteden alır." },
  { k: ['yunus | şişe burun | sise burun'], a: "Yunus zeki deniz memelisidir, sonar benzeri yankıyla yön bulur." },
  { k: ['ahtapot | sekiz kol'], a: "Ahtapotun sekiz kolu ve üç kalbi vardır, renk değiştirir." },
  { k: ['denizanasi | meduz'], a: "Denizanası yakıcı dokunaçlı saydam deniz canlısıdır." },
  { k: ['mercan | mercan resifi'], a: "Mercan resifleri denizlerin yağmur ormanı sayılır." },
  { k: ['karides'], a: "Karides küçük kabuklu deniz ürünüdür." },
  { k: ['istakoz'], a: "Istakoz kıskaçlı büyük kabukludur." },
  { k: ['palamut | torik'], a: "Palamut sonbaharda Karadeniz'den geçen göçmen balıktır." },
  { k: ['levrek'], a: "Levrek beyaz etli değerli deniz balığıdır." },
  { k: ['cupra | çipura'], a: "Çipura Ege'nin ünlü beyaz etli balığıdır." },
  { k: ['alabalik | dere alabaligi'], a: "Alabalık soğuk derelerde yaşayan tatlı su balığıdır." },
  { k: ['sazan'], a: "Sazan göl ve barajlarda yaşayan dayanıklı tatlı su balığıdır." },
  // Kuslar
  { k: ['baykus | gece kusu'], a: "Baykuş gece avlanan, başını geniş çevirebilen yırtıcı kuştur." },
  { k: ['leylek | hacileylek'], a: "Leylek baharda göçle gelen uzun bacaklı kuştur." },
  { k: ['karga | kuzgun fark'], a: "Karga problem çözebilen zeki kuştur." },
  { k: ['serce'], a: "Serçe şehirlerde yaşayan küçük ötücü kuştur." },
  { k: ['guvercin | posta guvercini'], a: "Posta güvercini eskiden haber taşımada kullanılırdı." },
  { k: ['papagan | muhabbet kusu'], a: "Papağan konuşmayı taklit edebilen renkli kuştur." },
  { k: ['tavus kusu'], a: "Tavus kuşu kuyruk tüylerini yelpaze gibi açar." },
  { k: ['flamingo | allı turna'], a: "Flamingo pembe rengini yediği karidesten alır." },
  { k: ['pelikan'], a: "Pelikan gagasındaki keseyle balık tutar." },
  { k: ['devkusu | devekuşu'], a: "Devekuşu uçamayan en büyük kuştur, hızlı koşar." },
  { k: ['marti'], a: "Martı deniz kıyılarında yaşayan beyaz-gri kuştur." },
  { k: ['sahin | dogan | atmaca'], a: "Şahin ve doğan hızlı dalış yapan yırtıcı kuşlardır." },
  // Bocekler
  { k: ['karinca | karinca yuvasi'], a: "Karınca kolonilerde yaşayan çalışkan böcektir." },
  { k: ['ugur bocegi'], a: "Uğur böceği yaprak biti yiyen faydalı böcektir." },
  { k: ['sinek | karasinek'], a: "Karasinek mikrop taşır, yiyecekler kapatılmalıdır." },
  { k: ['sivrisinek | sivri'], a: "Sivrisinek kan emer, durgun sularda ürer; cibinlik ve sineklik korur." },
  { k: ['cekirge'], a: "Çekirge uzun arka bacaklarıyla zıplayan böcektir." },
  { k: ['hamambocegi | kalorifer bocegi'], a: "Hamamböceği karanlık nemli yerleri sever, gıda hijyeniyle önlenir." },
  { k: ['orumcek agi | zehirli orumcek'], a: "Örümcekler ağ örüp böcek avlar, çoğu insana zararsızdır." },
  { k: ['akrep'], a: "Akrep kuyruğundaki iğneyle sokar; sokarsa soğuk uygulanıp doktora gidilir." },
  { k: ['ari kraliçe | kraliçe arı'], a: "Kraliçe arı kovanda yumurtlayan tek dişidir." },
  // Bitkiler
  { k: ['papatya | papatya cayi'], a: "Papatya çayı sakinleştirici bitki çayıdır." },
  { k: ['gul | gül yağı | gul yagi'], a: "Gül Isparta'da yağ için yetiştirilir." },
  { k: ['lale | lale devri'], a: "Lale Osmanlı'da simge çiçekti, Hollanda ile anılır." },
  { k: ['orkide | salebin cicegi'], a: "Orkide gösterişli çiçekli bitkidir, salep orkide kökündendir." },
  { k: ['aycicegi | cekirdek'], a: "Ayçiçeği yağlık tohum verir, güneşe döner." },
  { k: ['meshe | pelit'], a: "Meşe palamut veren dayanıklı ağaçtır." },
  { k: ['zeytin | zeytinyagi'], a: "Zeytin ve zeytinyağı Ege mutfağının temelidir." },
  { k: ['cinar | ulu agac'], a: "Çınar uzun ömürlü gölge ağacıdır." },
  { k: ['cam agaci | koza'], a: "Çam kozalaklı iğne yapraklı ağaçtır." },
  { k: ['kavak | servi'], a: "Kavak hızlı büyüyen ince uzun ağaçtır." },
  { k: ['incir | yemiş'], a: "İncir Aydın bölgesinin ünlü meyvesidir." },
  { k: ['nar | bereket'], a: "Nar bereket simgesi sayılan taneli meyvedir." },
  { k: ['kaktus | sukulent'], a: "Kaktüs suyu depolayıp kuraklığa dayanır." },
];
module.exports = NEW_ENTRIES;
