// Veritabani genisletme set 2: gezegenler + elementler + vitaminler
const NEW_ENTRIES = [
  { k: ['merkur | en kucuk gezegen'], a: "Merkür Güneş'e en yakın ve en küçük gezegendir." },
  { k: ['venus | coban yildizi'], a: "Venüs Güneş'e ikinci gezegendir, halk arasında Çoban Yıldızı denir." },
  { k: ['dunya kac yasinda | dunya yas'], a: "Dünya yaklaşık 4,5 milyar yaşındadır." },
  { k: ['jupiter | en buyuk gezegen'], a: "Jüpiter Güneş sisteminin en büyük gezegenidir." },
  { k: ['saturn | halkali gezegen', 'saturn halkalari'], a: "Satürn buz ve kaya parçalarından oluşan ünlü halkalarıyla bilinir." },
  { k: ['uranus | yan yatan gezegen'], a: "Uranüs eksenine yatık döndüğü için yan yatmış gibi görünür." },
  { k: ['neptun | en uzak gezegen'], a: "Neptün Güneş'e en uzak gezegendir." },
  { k: ['gunes nedir | gunes kac yasinda'], a: "Güneş orta büyüklükte bir yıldızdır, yaklaşık 5 milyar yıl daha parlayacak." },
  { k: ['ay dunyaya uzaklik | ay kac km'], a: "Ay Dünya'ya yaklaşık 384 bin kilometre uzaklıktadır." },
  // Elementler (sembol + kisa bilgi)
  { k: ['hidrojen | h elementi'], a: "Hidrojen (H) evrenin en hafif ve en bol elementidir." },
  { k: ['helyum | he elementi'], a: "Helyum (He) balonları uçuran, yanmayan hafif gazdır." },
  { k: ['oksijen | o elementi'], a: "Oksijen (O) soluduğumuz havanın yaklaşık beşte biridir." },
  { k: ['karbon | c elementi'], a: "Karbon (C) elmas ve kömürün ortak yapıtaşıdır, yaşamın temelidir." },
  { k: ['azot | n elementi'], a: "Azot (N) havanın yaklaşık yüzde 78'ini oluşturur." },
  { k: ['demir elementi | fe'], a: "Demir (Fe) kanımızdaki hemoglobinde ve çelikte bulunur." },
  { k: ['altin elementi | au', 'altin sembolu'], a: "Altının sembolü Au'dur, paslanmayan değerli madendir." },
  { k: ['gumus elementi | ag', 'gumus sembolu'], a: "Gümüşün sembolü Ag'dir, en iyi elektrik ileten madendir." },
  { k: ['bakir elementi | cu'], a: "Bakır (Cu) elektrik kablolarında kullanılan kırmızı madendir." },
  { k: ['aluminyum | al elementi'], a: "Alüminyum (Al) hafif olduğu için uçak ve içecek kutularında kullanılır." },
  { k: ['sodyum | na elementi'], a: "Sodyum (Na) sofra tuzunun (NaCl) yapıtaşıdır." },
  { k: ['potasyum | k elementi'], a: "Potasyum (K) muzda bol bulunur, kaslar için gereklidir." },
  { k: ['kalsiyum | ca elementi'], a: "Kalsiyum (Ca) kemik ve dişlerin yapıtaşıdır, sütte bol bulunur." },
  { k: ['klor | cl elementi'], a: "Klor (Cl) havuz suyunu mikroplardan temizlemekte kullanılır." },
  { k: ['silisyum | si elementi'], a: "Silisyum (Si) bilgisayar çiplerinin ham maddesidir." },
  { k: ['civa elementi | hg'], a: "Cıva (Hg) oda sıcaklığında sıvı olan tek madendir, zehirlidir." },
  { k: ['kursun elementi | pb'], a: "Kurşun (Pb) akülerde kullanılır, zehirli olduğu için dikkat gerekir." },
  { k: ['uranyum | u elementi'], a: "Uranyum (U) nükleer santrallerde yakıt olarak kullanılır." },
  { k: ['kukurt | s elementi'], a: "Kükürt (S) keskin kokulu sarı katıdır, kibrit ve barutta kullanılır." },
  { k: ['fosfor | p elementi'], a: "Fosfor (P) kemiklerde bulunur, kibrit ucunda kullanılır." },
  // Vitaminler
  { k: ['a vitamini | vitamin a'], a: "A vitamini göz sağlığı için gereklidir; havuç ve ıspanakta bulunur." },
  { k: ['b12 vitamini | vitamin b12'], a: "B12 vitamini kan yapımı için gereklidir; et, süt ve yumurtada bulunur." },
  { k: ['c vitamini | vitamin c'], a: "C vitamini bağışıklığı destekler; portakal, limon ve kivide bulunur." },
  { k: ['d vitamini | vitamin d'], a: "D vitamini güneş ışığıyla deride üretilir, kemikler için gereklidir." },
  { k: ['e vitamini | vitamin e'], a: "E vitamini hücreleri korur; kuruyemiş ve bitkisel yağlarda bulunur." },
  { k: ['k vitamini | vitamin k'], a: "K vitamini kanın pıhtılaşmasında görevlidir; yeşil yapraklılarda bulunur." },
  { k: ['demir eksikligi | kansizlik'], a: "Demir eksikliği halsizlik yapar; kırmızı et, mercimek ve pekmez iyi gelir. Şüphen varsa doktora danış." },
];
module.exports = NEW_ENTRIES;
